## Assignment 1: Path Analysis {- #a1}

For the first assignment, **you will work individually** to apply a *path model* that describes how several (observed)
variables could be causally related. 

### Required Components {- #a1_components}

The obligatory aspects of the first assignment are described below.

1. Choose a suitable dataset, and describe the data.
   - You can use any of the 8 datasets linked [below](#data_options).
   - Provide some form of citation for the data source
   - Provide descriptive statistics for important demographics (e.g., sex, age, SES) and the substantive variables that
   you will use to estimate your model.
1. State the [research question](#rq); define and explicate the theoretical path model.
   - This model must include, at least, three variables.
      1. Dependent variable (DV)
      1. Theoretically interesting independent variable/predictor (IV)
      1. Covariate/control variable
   - Your model can also include more than one of any type of variable.
      - We encourage using more than one IV and covariate.
   - Include a path diagram that represents your theoretical model.
   - Explain the conceptual fit between your theory and your model.
      - I.e., how does your model represent your theory?
1. Translate your theoretical path model into `lavaan` syntax, and estimate the 
model.
   - Submit the [(clean) R script](#analysis_script) along with your report.
      - Submit this R script as a separate file, not part of your report.
   - Include the lavaan syntax used to estimate your path models in your report.
      - Place these syntax snippets in [an appendix](#formatting).
1. Report the results of you analysis.
   - Evaluate the model [assumptions](#model_assumptions).
   - Provide relevant output in a [suitable format](#reporting_standards).
   - Include measures of explained variance for the dependent variables.
1. Discuss your findings.
   - Use your results to answer the research question.
   - Consider the strengths and limitations of your analysis.
   - Discuss any important decisions that could have influence your results.

### Evaluation {-}

See the [Grading](#assignment_grading) section below for more information on how Assignment 1 will be evaluated.

You can access an evaluation matrix for Assignment 1 [here](`r makeCourseUrl("assets/assignments/a1_guidelines.pdf")`).

- This matrix gives an indication of what level of work constitutes *insufficient*, *sufficient*, and *excellent*
responses to the five components described above.

### Submission {-}

Assignment 1 is due at 23:59 on Friday 9 October 2026.

- Submit your report via the *Assignments Page* on Brightspace.
