## Assignment Guidelines {-}

You will complete two data analysis projects in this course: an individual assignment covering *path analysis* and a
group assignment covering *structural equation modeling*. This section outlines the key requirements and logistical
points. The following sections provide more detail.

---

### Assignment 1: Path Analysis {- #a1}

For the first assignment, **you will work individually** to apply a *path model* that describes how several (observed)
variables could be causally related. 

#### Required Components {- #a1_components}

The obligatory aspects of the first assignment are described below.

1. Choose a suitable dataset, and describe the data.
   - You can use any of the 8 datasets linked [below](#data_options).
   - Provide some form of citation for the data source
   - Provide descriptive statistics for important demographics (e.g., sex, age, SES) and the substantive variables that
   you will use to estimate your model.
1. State the [research question](#rq); define and explicate the theoretical path model.
   - This model must include, at least, three variables.
      1. Dependent variable (DV)
      1. Theoretically interesting independent variable/predictor (IV)
      1. Covariate/control variable
   - Your model can also include more than one of any type of variable.
      - We encourage using more than one IV and covariate.
   - Include a path diagram that represents your theoretical model.
   - Explain the conceptual fit between your theory and your model.
      - I.e., how does your model represent your theory?
1. Translate your theoretical path model into `lavaan` syntax, and estimate the 
model.
   - Submit the [(clean) R script](#analysis_script) along with your report.
      - Submit this R script as a separate file, not part of your report.
   - Include the lavaan syntax used to estimate your path models in your report.
      - Place these syntax snippets in [an appendix](#formatting).
1. Report the results of you analysis.
   - Evaluate the model [assumptions](#model_assumptions).
   - Provide relevant output in a [suitable format](#reporting_standards).
   - Include measures of explained variance for the dependent variables.
1. Discuss your findings.
   - Use your results to answer the research question.
   - Consider the strengths and limitations of your analysis.
   - Discuss any important decisions that could have influence your results.

#### Evaluation {-}

See the [Grading](#assignment_grading) section below for more information on how Assignment 1 will be evaluated.

You can access an evaluation matrix for Assignment 1 [here](`r makeCourseUrl("assets/assignments/a1_guidelines.pdf")`).

- This matrix gives an indication of what level of work constitutes *insufficient*, *sufficient*, and *excellent*
responses to the five components described above.

#### Submission {-}

Assignment 1 is due at 23:59 on Friday 9 October 2026.

- Submit your report via the *Assignments Page* on Brightspace.

---

### Assignment 2: Structural Equation Modeling {- #a2}

In the second assignment, **you will work in groups** to apply a structural equation model (SEM) that describes how
several (latent) variables could be causally related. 

Before estimating your SEM, you will evaluate the validity of your latent variables by using confirmatory factor
analysis (CFA) to test your hypothesized measurement model. You will include both your CFA and SEM results in your
write-up. The inferences that you draw from an SEM are only valid if the underlying measurement model holds. So, the
first step in reporting any SEM (at least any SEM that includes estimated latent constructs) is demonstrating the
validity of the measurement model by reporting your CFA results.

#### Required Components {- #a2_components}

The obligatory aspects of the second assignment are described below.

1. Choose a suitable dataset, and describe the data.
	 - Unless you have a good reason to switch, you should work with the same data that someone in your group analyzed for
	 Assignment 1.
   - If you need to switch, you can use any of the 8 datasets linked [below](#data_options).
1. State the [research question](#rq); define and explicate the theoretical SEM. 
   - The structural component of this model must include, at least, three variables.
   - The structural model must include, at least, two latent variables.
   - At least one independent variable in your model must be latent.
   - You do not need to explicate a separate theory/research question/hypothesis for your measurement model.
1. Translate your hypothesized measurement model into **lavaan** syntax, and estimate the CFA model.
<!--
   - Submit the [(clean) R script](#analysis_script) along with your report.
      - Submit this R script as a separate file, not part of your report.
   - Include the lavaan syntax used to estimate your CFA models in your report.
      - Place these syntax snippets in [an appendix](#formatting).
-->
1. Report the results of your CFA.
   - Provide relevant output in a [suitable format](#reporting_standards).
   - Include suitable parameter estimates.
   - Include measures of explained variance for the observed indicators.
   - Include measures of model fit.
   - Evaluate the model [assumptions](#model_assumptions).
1. Translate your theoretical SEM into **lavaan** syntax, and estimate the model.
<!--
   - Submit the [(clean) R script](#analysis_script) along with your report.
      - Submit this R script as a separate file, not part of your report.
   - Include the lavaan syntax used to estimate your SEM model in your report.
      - Place these syntax snippets in [an appendix](#formatting).
-->
1. Report the results of your SEM.
   - Provide relevant output in a [suitable format](#reporting_standards).
   - Include suitable parameter estimates.
   - Include measures of model fit.
   - Include measures of explained variance for the latent dependent variables.
1. Discuss your findings.
   - Use your results to answer the research question.
   - Consider the strengths and limitations of your analysis.
   - Discuss any important decisions that could have influence your results.

#### Evaluation {-}

***Details coming soon!***

<!--
See the [Grading](#assignment_grading) section below for more information on how Assignment 2 will be evaluated.

You can access an evaluation matrix for Assignment 2 [here](`r makeCourseUrl("assets/assignments/a2_guidelines.pdf")`).

- This matrix gives an indication of what level of work constitutes *insufficient*, *sufficient*, and *excellent*
responses to the seven components described above.
-->

#### Submission {-}

***Details coming soon!***

<!--
Assignment 2 is due at 23:59 on Sunday 2 November 2025.

- Submit your report via the *Assignments Page* on Brightspace.
-->

---

### Data {- #data_options}

Below, you can find links to a few suitable datasets that you can use for the assignments.

- You *must* use one of the following datasets. You may not choose your own data from the wild.

#### Coping with Covid {-} 

- [Dataset][covid_data]
- [Codebook][covid_codebook]
- [Pre-Registration][covid_reg]

#### Feminist Perspectives Scale {-}

- [Dataset][fem_data]
- [Article][fem_paper]

#### Hypersensitive Narcissism Scale & Dirty Dozen {-}

- [Dataset][hsns_dd_data]
- [HSNS Article][hsns_paper]
- [DD Article][dd_paper]

#### Kentucky Inventory of Mindfulness Skills {-}

- [Dataset][kims_data]
- [Article][kims_paper]

#### Depression Anxiety Stress Scale {-}

- [Dataset][dass_data]
- [DASS Information][dass_info]

#### Nomophobia {-}

- [Dataset][nomophobia_data]

#### Recycled Water Acceptance {-}

- [Dataset][rwa_data]
- [Article][rwa_paper]
