<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>4.4 In-Class Exercises | Introduction to Structural Equation Modeling</title>
  <meta name="description" content="4.4 In-Class Exercises | Introduction to Structural Equation Modeling" />
  <meta name="generator" content="bookdown 0.48 and GitBook 2.6.7" />

  <meta property="og:title" content="4.4 In-Class Exercises | Introduction to Structural Equation Modeling" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="4.4 In-Class Exercises | Introduction to Structural Equation Modeling" />
  
  
  

<meta name="author" content="Kyle M. Lang" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="at-home-exercises-3.html"/>
<link rel="next" href="cfa-ii.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="libs/pagedtable-1.1/js/pagedtable.js"></script>
<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="assets/html/style.css" type="text/css" />
<link rel="stylesheet" href="font-awesome.min.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./index.html">Introduction to SEM</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Course Information</a>
<ul>
<li class="chapter" data-level="" data-path="acknowledgement.html"><a href="acknowledgement.html"><i class="fa fa-check"></i>Acknowledgement</a></li>
<li class="chapter" data-level="" data-path="instructors.html"><a href="instructors.html"><i class="fa fa-check"></i>Instructors</a></li>
<li class="chapter" data-level="" data-path="course-overview.html"><a href="course-overview.html"><i class="fa fa-check"></i>Course overview</a></li>
<li class="chapter" data-level="" data-path="schedule.html"><a href="schedule.html"><i class="fa fa-check"></i>Schedule</a></li>
<li class="chapter" data-level="" data-path="learning-goals.html"><a href="learning-goals.html"><i class="fa fa-check"></i>Learning goals</a>
<ul>
<li class="chapter" data-level="" data-path="learning-goals.html"><a href="learning-goals.html#background"><i class="fa fa-check"></i>Background knowledge</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="resources.html"><a href="resources.html"><i class="fa fa-check"></i>Resources</a>
<ul>
<li class="chapter" data-level="" data-path="resources.html"><a href="resources.html#literature"><i class="fa fa-check"></i>Literature</a></li>
<li class="chapter" data-level="" data-path="resources.html"><a href="resources.html#reading-questions"><i class="fa fa-check"></i>Reading questions</a></li>
<li class="chapter" data-level="" data-path="resources.html"><a href="resources.html#software"><i class="fa fa-check"></i>Software</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="logistics.html"><a href="logistics.html"><i class="fa fa-check"></i>Logistics</a>
<ul>
<li class="chapter" data-level="" data-path="logistics.html"><a href="logistics.html#weekly-preparation"><i class="fa fa-check"></i>Weekly preparation</a></li>
<li class="chapter" data-level="" data-path="logistics.html"><a href="logistics.html#evaluation"><i class="fa fa-check"></i>Evaluation</a></li>
<li class="chapter" data-level="" data-path="logistics.html"><a href="logistics.html#attendance"><i class="fa fa-check"></i>Attendance</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="ai_policy.html"><a href="ai_policy.html"><i class="fa fa-check"></i>Using GenAI</a>
<ul>
<li class="chapter" data-level="" data-path="ai_policy.html"><a href="ai_policy.html#ai-index"><i class="fa fa-check"></i>AI index</a></li>
<li class="chapter" data-level="" data-path="ai_policy.html"><a href="ai_policy.html#acceptable-usage-in-this-course"><i class="fa fa-check"></i>Acceptable usage in this course</a></li>
<li class="chapter" data-level="" data-path="ai_policy.html"><a href="ai_policy.html#including-ai-generated-content-in-your-work"><i class="fa fa-check"></i>Including AI-generated content in your work</a></li>
<li class="chapter" data-level="" data-path="ai_policy.html"><a href="ai_policy.html#referencing-and-academic-integrity"><i class="fa fa-check"></i>Referencing and academic integrity</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="assignments.html"><a href="assignments.html"><i class="fa fa-check"></i>Assignments</a>
<ul>
<li class="chapter" data-level="" data-path="assignment-guidelines.html"><a href="assignment-guidelines.html"><i class="fa fa-check"></i>Assignment Guidelines</a>
<ul>
<li class="chapter" data-level="" data-path="assignment-guidelines.html"><a href="assignment-guidelines.html#a1"><i class="fa fa-check"></i>Assignment 1: Path Analysis</a></li>
<li class="chapter" data-level="" data-path="assignment-guidelines.html"><a href="assignment-guidelines.html#a2"><i class="fa fa-check"></i>Assignment 2: Structural Equation Modeling</a></li>
<li class="chapter" data-level="" data-path="assignment-guidelines.html"><a href="assignment-guidelines.html#data_options"><i class="fa fa-check"></i>Data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="elaboration-tips.html"><a href="elaboration-tips.html"><i class="fa fa-check"></i>Elaboration &amp; Tips</a>
<ul>
<li class="chapter" data-level="" data-path="elaboration-tips.html"><a href="elaboration-tips.html#progression"><i class="fa fa-check"></i>Progression</a></li>
<li class="chapter" data-level="" data-path="elaboration-tips.html"><a href="elaboration-tips.html#rq"><i class="fa fa-check"></i>Theoretical Model &amp; Research Question</a></li>
<li class="chapter" data-level="" data-path="elaboration-tips.html"><a href="elaboration-tips.html#model_assumptions"><i class="fa fa-check"></i>Assumptions</a></li>
<li class="chapter" data-level="" data-path="elaboration-tips.html"><a href="elaboration-tips.html#reporting_standards"><i class="fa fa-check"></i>Reporting Standards</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="procedures.html"><a href="procedures.html"><i class="fa fa-check"></i>Procedures</a>
<ul>
<li class="chapter" data-level="" data-path="procedures.html"><a href="procedures.html#formatting"><i class="fa fa-check"></i>Formatting</a></li>
<li class="chapter" data-level="" data-path="procedures.html"><a href="procedures.html#length"><i class="fa fa-check"></i>Length</a></li>
<li class="chapter" data-level="" data-path="procedures.html"><a href="procedures.html#submission-2"><i class="fa fa-check"></i>Submission</a></li>
<li class="chapter" data-level="" data-path="procedures.html"><a href="procedures.html#rules"><i class="fa fa-check"></i>Rules</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="assignment_grading.html"><a href="assignment_grading.html"><i class="fa fa-check"></i>Grading</a>
<ul>
<li class="chapter" data-level="" data-path="assignment_grading.html"><a href="assignment_grading.html#assignment-1"><i class="fa fa-check"></i>Assignment 1</a></li>
<li class="chapter" data-level="" data-path="assignment_grading.html"><a href="assignment_grading.html#assignment-2"><i class="fa fa-check"></i>Assignment 2</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="software-setup.html"><a href="software-setup.html"><i class="fa fa-check"></i>Software Setup</a>
<ul>
<li class="chapter" data-level="" data-path="typographic-conventions.html"><a href="typographic-conventions.html"><i class="fa fa-check"></i>Typographic Conventions</a></li>
<li class="chapter" data-level="" data-path="installing-software.html"><a href="installing-software.html"><i class="fa fa-check"></i>Installing software</a>
<ul>
<li class="chapter" data-level="" data-path="installing-software.html"><a href="installing-software.html#installing-r"><i class="fa fa-check"></i>Installing R</a></li>
<li class="chapter" data-level="" data-path="installing-software.html"><a href="installing-software.html#installing-rstudio"><i class="fa fa-check"></i>Installing RStudio</a></li>
<li class="chapter" data-level="" data-path="installing-software.html"><a href="installing-software.html#installing-packages"><i class="fa fa-check"></i>Installing packages</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="course-data.html"><a href="course-data.html"><i class="fa fa-check"></i>Course Data</a>
<ul>
<li class="chapter" data-level="" data-path="note-on-data-updates.html"><a href="note-on-data-updates.html"><i class="fa fa-check"></i>Note on Data Updates</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction-to-r.html"><a href="introduction-to-r.html"><i class="fa fa-check"></i><b>1</b> Introduction to R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="lecture.html"><a href="lecture.html"><i class="fa fa-check"></i><b>1.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="lecture.html"><a href="lecture.html#recordings"><i class="fa fa-check"></i><b>1.1.1</b> Recordings</a></li>
<li class="chapter" data-level="1.1.2" data-path="lecture.html"><a href="lecture.html#slides"><i class="fa fa-check"></i><b>1.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="reading.html"><a href="reading.html"><i class="fa fa-check"></i><b>1.2</b> Reading</a></li>
<li class="chapter" data-level="1.3" data-path="at-home-exercises.html"><a href="at-home-exercises.html"><i class="fa fa-check"></i><b>1.3</b> At-Home Exercises</a></li>
<li class="chapter" data-level="1.4" data-path="in-class-exercises.html"><a href="in-class-exercises.html"><i class="fa fa-check"></i><b>1.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="" data-path="in-class-exercises.html"><a href="in-class-exercises.html#recap"><i class="fa fa-check"></i>Recap</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="statistical-modeling-path-analysis.html"><a href="statistical-modeling-path-analysis.html"><i class="fa fa-check"></i><b>2</b> Statistical Modeling &amp; Path Analysis</a>
<ul>
<li class="chapter" data-level="2.1" data-path="lecture-1.html"><a href="lecture-1.html"><i class="fa fa-check"></i><b>2.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="lecture-1.html"><a href="lecture-1.html#recordings-1"><i class="fa fa-check"></i><b>2.1.1</b> Recordings</a></li>
<li class="chapter" data-level="2.1.2" data-path="lecture-1.html"><a href="lecture-1.html#slides-1"><i class="fa fa-check"></i><b>2.1.2</b> Slides</a></li>
<li class="chapter" data-level="2.1.3" data-path="lecture-1.html"><a href="lecture-1.html#materials-from-the-lecture-meeting"><i class="fa fa-check"></i><b>2.1.3</b> Materials from the lecture meeting</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="reading-1.html"><a href="reading-1.html"><i class="fa fa-check"></i><b>2.2</b> Reading</a>
<ul>
<li class="chapter" data-level="" data-path="reading-1.html"><a href="reading-1.html#reference"><i class="fa fa-check"></i>Reference</a></li>
<li class="chapter" data-level="" data-path="reading-1.html"><a href="reading-1.html#questions"><i class="fa fa-check"></i>Questions</a></li>
<li class="chapter" data-level="" data-path="reading-1.html"><a href="reading-1.html#suggested-reading-optional"><i class="fa fa-check"></i>Suggested Reading (Optional)</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html"><i class="fa fa-check"></i><b>2.3</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#setup"><i class="fa fa-check"></i><b>2.3.1</b> Setup</a></li>
<li class="chapter" data-level="2.3.2" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#section"><i class="fa fa-check"></i><b>2.3.2</b> </a></li>
<li class="chapter" data-level="2.3.3" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#section-1"><i class="fa fa-check"></i><b>2.3.3</b> </a></li>
<li class="chapter" data-level="2.3.4" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#slr1"><i class="fa fa-check"></i><b>2.3.4</b> </a></li>
<li class="chapter" data-level="2.3.5" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#slr2"><i class="fa fa-check"></i><b>2.3.5</b> </a></li>
<li class="chapter" data-level="2.3.6" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#slr3"><i class="fa fa-check"></i><b>2.3.6</b> </a></li>
<li class="chapter" data-level="2.3.7" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#mlr"><i class="fa fa-check"></i><b>2.3.7</b> </a></li>
<li class="chapter" data-level="2.3.8" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#section-2"><i class="fa fa-check"></i><b>2.3.8</b> </a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="in-class-exercises-1.html"><a href="in-class-exercises-1.html"><i class="fa fa-check"></i><b>2.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="in-class-exercises-1.html"><a href="in-class-exercises-1.html#setup-1"><i class="fa fa-check"></i><b>2.4.1</b> Setup</a></li>
<li class="chapter" data-level="2.4.2" data-path="in-class-exercises-1.html"><a href="in-class-exercises-1.html#data-exploration"><i class="fa fa-check"></i><b>2.4.2</b> Data Exploration</a></li>
<li class="chapter" data-level="2.4.3" data-path="in-class-exercises-1.html"><a href="in-class-exercises-1.html#linear-modeling"><i class="fa fa-check"></i><b>2.4.3</b> Linear Modeling</a></li>
<li class="chapter" data-level="2.4.4" data-path="in-class-exercises-1.html"><a href="in-class-exercises-1.html#categorical-ivs"><i class="fa fa-check"></i><b>2.4.4</b> Categorical IVs</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="mediation-moderation.html"><a href="mediation-moderation.html"><i class="fa fa-check"></i><b>3</b> Mediation &amp; Moderation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="lecture-2.html"><a href="lecture-2.html"><i class="fa fa-check"></i><b>3.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="lecture-2.html"><a href="lecture-2.html#recordings-2"><i class="fa fa-check"></i><b>3.1.1</b> Recordings</a></li>
<li class="chapter" data-level="3.1.2" data-path="lecture-2.html"><a href="lecture-2.html#slides-2"><i class="fa fa-check"></i><b>3.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="reading-2.html"><a href="reading-2.html"><i class="fa fa-check"></i><b>3.2</b> Reading</a>
<ul>
<li class="chapter" data-level="" data-path="reading-2.html"><a href="reading-2.html#reference-1"><i class="fa fa-check"></i>Reference</a></li>
<li class="chapter" data-level="" data-path="reading-2.html"><a href="reading-2.html#questions-1"><i class="fa fa-check"></i>Questions</a></li>
<li class="chapter" data-level="" data-path="reading-2.html"><a href="reading-2.html#reference-2"><i class="fa fa-check"></i>Reference</a></li>
<li class="chapter" data-level="" data-path="reading-2.html"><a href="reading-2.html#questions-2"><i class="fa fa-check"></i>Questions</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="at-home-exercises-2.html"><a href="at-home-exercises-2.html"><i class="fa fa-check"></i><b>3.3</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="at-home-exercises-2.html"><a href="at-home-exercises-2.html#setup-2"><i class="fa fa-check"></i><b>3.3.1</b> Setup</a></li>
<li class="chapter" data-level="3.3.2" data-path="at-home-exercises-2.html"><a href="at-home-exercises-2.html#mediation"><i class="fa fa-check"></i><b>3.3.2</b> Mediation</a></li>
<li class="chapter" data-level="3.3.3" data-path="at-home-exercises-2.html"><a href="at-home-exercises-2.html#moderation"><i class="fa fa-check"></i><b>3.3.3</b> Moderation</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="in-class-exercises-2.html"><a href="in-class-exercises-2.html"><i class="fa fa-check"></i><b>3.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="in-class-exercises-2.html"><a href="in-class-exercises-2.html#setup-3"><i class="fa fa-check"></i><b>3.4.1</b> Setup</a></li>
<li class="chapter" data-level="3.4.2" data-path="in-class-exercises-2.html"><a href="in-class-exercises-2.html#mediation-1"><i class="fa fa-check"></i><b>3.4.2</b> Mediation</a></li>
<li class="chapter" data-level="3.4.3" data-path="in-class-exercises-2.html"><a href="in-class-exercises-2.html#moderation-1"><i class="fa fa-check"></i><b>3.4.3</b> Moderation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="cfa-i.html"><a href="cfa-i.html"><i class="fa fa-check"></i><b>4</b> CFA I</a>
<ul>
<li class="chapter" data-level="4.1" data-path="lecture-3.html"><a href="lecture-3.html"><i class="fa fa-check"></i><b>4.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="lecture-3.html"><a href="lecture-3.html#recordings-3"><i class="fa fa-check"></i><b>4.1.1</b> Recordings</a></li>
<li class="chapter" data-level="4.1.2" data-path="lecture-3.html"><a href="lecture-3.html#slides-3"><i class="fa fa-check"></i><b>4.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="reading-3.html"><a href="reading-3.html"><i class="fa fa-check"></i><b>4.2</b> Reading</a>
<ul>
<li class="chapter" data-level="" data-path="reading-3.html"><a href="reading-3.html#reference-3"><i class="fa fa-check"></i>Reference</a></li>
<li class="chapter" data-level="" data-path="reading-3.html"><a href="reading-3.html#questions-3"><i class="fa fa-check"></i>Questions</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html"><i class="fa fa-check"></i><b>4.3</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#setup-4"><i class="fa fa-check"></i><b>4.3.1</b> Setup</a></li>
<li class="chapter" data-level="4.3.2" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-45"><i class="fa fa-check"></i><b>4.3.2</b> </a></li>
<li class="chapter" data-level="4.3.3" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-46"><i class="fa fa-check"></i><b>4.3.3</b> </a></li>
<li class="chapter" data-level="4.3.4" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#df"><i class="fa fa-check"></i><b>4.3.4</b> </a></li>
<li class="chapter" data-level="4.3.5" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#cfaSyntax1"><i class="fa fa-check"></i><b>4.3.5</b> </a></li>
<li class="chapter" data-level="4.3.6" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#cfaEstimationHome1"><i class="fa fa-check"></i><b>4.3.6</b> </a></li>
<li class="chapter" data-level="4.3.7" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-47"><i class="fa fa-check"></i><b>4.3.7</b> </a></li>
<li class="chapter" data-level="4.3.8" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-48"><i class="fa fa-check"></i><b>4.3.8</b> </a></li>
<li class="chapter" data-level="4.3.9" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-49"><i class="fa fa-check"></i><b>4.3.9</b> </a></li>
<li class="chapter" data-level="4.3.10" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#cfaSyntax2"><i class="fa fa-check"></i><b>4.3.10</b> </a></li>
<li class="chapter" data-level="4.3.11" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#cfaEstimation2"><i class="fa fa-check"></i><b>4.3.11</b> </a></li>
<li class="chapter" data-level="4.3.12" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-50"><i class="fa fa-check"></i><b>4.3.12</b> </a></li>
<li class="chapter" data-level="4.3.13" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-51"><i class="fa fa-check"></i><b>4.3.13</b> </a></li>
<li class="chapter" data-level="4.3.14" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-52"><i class="fa fa-check"></i><b>4.3.14</b> </a></li>
<li class="chapter" data-level="4.3.15" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#cfaEstimation3"><i class="fa fa-check"></i><b>4.3.15</b> </a></li>
<li class="chapter" data-level="4.3.16" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-53"><i class="fa fa-check"></i><b>4.3.16</b> </a></li>
<li class="chapter" data-level="4.3.17" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-54"><i class="fa fa-check"></i><b>4.3.17</b> </a></li>
<li class="chapter" data-level="4.3.18" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-55"><i class="fa fa-check"></i><b>4.3.18</b> </a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html"><i class="fa fa-check"></i><b>4.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-56"><i class="fa fa-check"></i><b>4.4.1</b> </a></li>
<li class="chapter" data-level="4.4.2" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#dfClass"><i class="fa fa-check"></i><b>4.4.2</b> </a></li>
<li class="chapter" data-level="4.4.3" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#cfaSyntaxClass1"><i class="fa fa-check"></i><b>4.4.3</b> </a></li>
<li class="chapter" data-level="4.4.4" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#cfaEstimationClass1"><i class="fa fa-check"></i><b>4.4.4</b> </a></li>
<li class="chapter" data-level="4.4.5" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-57"><i class="fa fa-check"></i><b>4.4.5</b> </a></li>
<li class="chapter" data-level="4.4.6" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-58"><i class="fa fa-check"></i><b>4.4.6</b> </a></li>
<li class="chapter" data-level="4.4.7" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-59"><i class="fa fa-check"></i><b>4.4.7</b> </a></li>
<li class="chapter" data-level="4.4.8" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-60"><i class="fa fa-check"></i><b>4.4.8</b> </a></li>
<li class="chapter" data-level="4.4.9" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-61"><i class="fa fa-check"></i><b>4.4.9</b> </a></li>
<li class="chapter" data-level="4.4.10" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-62"><i class="fa fa-check"></i><b>4.4.10</b> </a></li>
<li class="chapter" data-level="4.4.11" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#cfaEstimationClass2"><i class="fa fa-check"></i><b>4.4.11</b> </a></li>
<li class="chapter" data-level="4.4.12" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-63"><i class="fa fa-check"></i><b>4.4.12</b> </a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="cfa-ii.html"><a href="cfa-ii.html"><i class="fa fa-check"></i><b>5</b> CFA II</a>
<ul>
<li class="chapter" data-level="5.1" data-path="lecture-4.html"><a href="lecture-4.html"><i class="fa fa-check"></i><b>5.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="lecture-4.html"><a href="lecture-4.html#recordings-4"><i class="fa fa-check"></i><b>5.1.1</b> Recordings</a></li>
<li class="chapter" data-level="5.1.2" data-path="lecture-4.html"><a href="lecture-4.html#slides-4"><i class="fa fa-check"></i><b>5.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="reading-4.html"><a href="reading-4.html"><i class="fa fa-check"></i><b>5.2</b> Reading</a>
<ul>
<li class="chapter" data-level="" data-path="reading-4.html"><a href="reading-4.html#references"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html"><i class="fa fa-check"></i><b>5.3</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#section-64"><i class="fa fa-check"></i><b>5.3.1</b> </a></li>
<li class="chapter" data-level="5.3.2" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#cfaSyntax"><i class="fa fa-check"></i><b>5.3.2</b> </a></li>
<li class="chapter" data-level="5.3.3" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#estimateCfa3F"><i class="fa fa-check"></i><b>5.3.3</b> </a></li>
<li class="chapter" data-level="5.3.4" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#section-65"><i class="fa fa-check"></i><b>5.3.4</b> </a></li>
<li class="chapter" data-level="5.3.5" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#section-66"><i class="fa fa-check"></i><b>5.3.5</b> </a></li>
<li class="chapter" data-level="5.3.6" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#estimateCfa1F"><i class="fa fa-check"></i><b>5.3.6</b> </a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html"><i class="fa fa-check"></i><b>5.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#basic-cfa"><i class="fa fa-check"></i><b>5.4.1</b> Basic CFA</a></li>
<li class="chapter" data-level="5.4.2" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#post-hoc-model-modifications"><i class="fa fa-check"></i><b>5.4.2</b> Post-Hoc Model Modifications</a></li>
<li class="chapter" data-level="5.4.3" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#model-comparisons"><i class="fa fa-check"></i><b>5.4.3</b> Model Comparisons</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="extra-resources.html"><a href="extra-resources.html"><i class="fa fa-check"></i><b>5.5</b> Extra Resources</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="fall-break.html"><a href="fall-break.html"><i class="fa fa-check"></i><b>6</b> Fall Break</a></li>
<li class="chapter" data-level="7" data-path="full-sem.html"><a href="full-sem.html"><i class="fa fa-check"></i><b>7</b> Full SEM</a>
<ul>
<li class="chapter" data-level="7.1" data-path="lecture-5.html"><a href="lecture-5.html"><i class="fa fa-check"></i><b>7.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="lecture-5.html"><a href="lecture-5.html#recording"><i class="fa fa-check"></i><b>7.1.1</b> Recording</a></li>
<li class="chapter" data-level="7.1.2" data-path="lecture-5.html"><a href="lecture-5.html#slides-5"><i class="fa fa-check"></i><b>7.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="reading-5.html"><a href="reading-5.html"><i class="fa fa-check"></i><b>7.2</b> Reading</a>
<ul>
<li class="chapter" data-level="" data-path="reading-5.html"><a href="reading-5.html#reference-4"><i class="fa fa-check"></i>Reference</a></li>
<li class="chapter" data-level="" data-path="reading-5.html"><a href="reading-5.html#questions-4"><i class="fa fa-check"></i>Questions</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="at-home-exercises-5.html"><a href="at-home-exercises-5.html"><i class="fa fa-check"></i><b>7.3</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="at-home-exercises-5.html"><a href="at-home-exercises-5.html#section-76"><i class="fa fa-check"></i><b>7.3.1</b> </a></li>
<li class="chapter" data-level="7.3.2" data-path="at-home-exercises-5.html"><a href="at-home-exercises-5.html#section-77"><i class="fa fa-check"></i><b>7.3.2</b> </a></li>
<li class="chapter" data-level="7.3.3" data-path="at-home-exercises-5.html"><a href="at-home-exercises-5.html#section-78"><i class="fa fa-check"></i><b>7.3.3</b> </a></li>
<li class="chapter" data-level="7.3.4" data-path="at-home-exercises-5.html"><a href="at-home-exercises-5.html#semEstimation"><i class="fa fa-check"></i><b>7.3.4</b> </a></li>
<li class="chapter" data-level="7.3.5" data-path="at-home-exercises-5.html"><a href="at-home-exercises-5.html#section-79"><i class="fa fa-check"></i><b>7.3.5</b> </a></li>
<li class="chapter" data-level="7.3.6" data-path="at-home-exercises-5.html"><a href="at-home-exercises-5.html#section-80"><i class="fa fa-check"></i><b>7.3.6</b> </a></li>
<li class="chapter" data-level="7.3.7" data-path="at-home-exercises-5.html"><a href="at-home-exercises-5.html#section-81"><i class="fa fa-check"></i><b>7.3.7</b> </a></li>
<li class="chapter" data-level="7.3.8" data-path="at-home-exercises-5.html"><a href="at-home-exercises-5.html#section-82"><i class="fa fa-check"></i><b>7.3.8</b> </a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html"><i class="fa fa-check"></i><b>7.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html#section-83"><i class="fa fa-check"></i><b>7.4.1</b> </a></li>
<li class="chapter" data-level="7.4.2" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html#toraCFA"><i class="fa fa-check"></i><b>7.4.2</b> </a></li>
<li class="chapter" data-level="7.4.3" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html#section-84"><i class="fa fa-check"></i><b>7.4.3</b> </a></li>
<li class="chapter" data-level="7.4.4" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html#tora1Estimation"><i class="fa fa-check"></i><b>7.4.4</b> </a></li>
<li class="chapter" data-level="7.4.5" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html#section-85"><i class="fa fa-check"></i><b>7.4.5</b> </a></li>
<li class="chapter" data-level="7.4.6" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html#updatedModel"><i class="fa fa-check"></i><b>7.4.6</b> </a></li>
<li class="chapter" data-level="7.4.7" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html#section-86"><i class="fa fa-check"></i><b>7.4.7</b> </a></li>
<li class="chapter" data-level="7.4.8" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html#section-87"><i class="fa fa-check"></i><b>7.4.8</b> </a></li>
<li class="chapter" data-level="7.4.9" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html#section-88"><i class="fa fa-check"></i><b>7.4.9</b> </a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="multiple-group-models.html"><a href="multiple-group-models.html"><i class="fa fa-check"></i><b>8</b> Multiple Group Models</a>
<ul>
<li class="chapter" data-level="8.1" data-path="lecture-6.html"><a href="lecture-6.html"><i class="fa fa-check"></i><b>8.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="lecture-6.html"><a href="lecture-6.html#recordings-5"><i class="fa fa-check"></i><b>8.1.1</b> Recordings</a></li>
<li class="chapter" data-level="8.1.2" data-path="lecture-6.html"><a href="lecture-6.html#slides-6"><i class="fa fa-check"></i><b>8.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="reading-6.html"><a href="reading-6.html"><i class="fa fa-check"></i><b>8.2</b> Reading</a></li>
<li class="chapter" data-level="8.3" data-path="at-home-exercises-6.html"><a href="at-home-exercises-6.html"><i class="fa fa-check"></i><b>8.3</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="at-home-exercises-6.html"><a href="at-home-exercises-6.html#mgPathAnalysis"><i class="fa fa-check"></i><b>8.3.1</b> Multiple-Group Path Analysis</a></li>
<li class="chapter" data-level="8.3.2" data-path="at-home-exercises-6.html"><a href="at-home-exercises-6.html#mgCFA"><i class="fa fa-check"></i><b>8.3.2</b> Multiple-Group CFA</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="in-class-exercises-6.html"><a href="in-class-exercises-6.html"><i class="fa fa-check"></i><b>8.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="in-class-exercises-6.html"><a href="in-class-exercises-6.html#setup-5"><i class="fa fa-check"></i><b>8.4.1</b> Setup</a></li>
<li class="chapter" data-level="8.4.2" data-path="in-class-exercises-6.html"><a href="in-class-exercises-6.html#w8MeasurementInvariance"><i class="fa fa-check"></i><b>8.4.2</b> Measurement Invariance</a></li>
<li class="chapter" data-level="8.4.3" data-path="in-class-exercises-6.html"><a href="in-class-exercises-6.html#testing-between-group-differences"><i class="fa fa-check"></i><b>8.4.3</b> Testing Between-Group Differences</a></li>
<li class="chapter" data-level="8.4.4" data-path="in-class-exercises-6.html"><a href="in-class-exercises-6.html#multiple-group-sem-for-moderation"><i class="fa fa-check"></i><b>8.4.4</b> Multiple-Group SEM for Moderation</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to Structural Equation Modeling</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="in-class-exercises-3" class="section level2 hasAnchor" number="4.4">
<h2><span class="header-section-number">4.4</span> In-Class Exercises<a href="in-class-exercises-3.html#in-class-exercises-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>For this week’s in-class exercises, we’ll continue modeling the Cattell 16PF items using CFA. We will use the same
dataset that you analyzed in the at-home exercises.</p>
<ul>
<li><a href="https://surfdrive.surf.nl/files/index.php/s/1hLlshF9xF0rpJH">cattell</a></li>
<li>You can find a codebook for the dataset <a href="data/16PF/codebook.html">here</a></li>
</ul>
<hr />
<div id="section-56" class="section level3" number="4.4.1">
<h3><span class="header-section-number">4.4.1</span> </h3>
<p>Load the <em>cattell</em> data.</p>
<ul>
<li>The relevant data are contained in the [<em>canttell.rds</em>][cattell_data] file.</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="in-class-exercises-3.html#cb165-1" tabindex="-1"></a>dataDir <span class="ot">&lt;-</span> <span class="st">&quot;data&quot;</span></span>
<span id="cb165-2"><a href="in-class-exercises-3.html#cb165-2" tabindex="-1"></a>cattell <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(here<span class="sc">::</span><span class="fu">here</span>(dataDir, <span class="st">&quot;cattell.rds&quot;</span>))</span></code></pre></div>
</details>
<hr />
<p>In the following exercises, we’ll work primarily with the four-factor CFA shown in the following path diagram. This CFA
models the measurement of the <em>Warmth</em>, <em>Liveliness</em>, <em>Vigilance</em>, and <em>Tension</em> factors from the 16PF.</p>
<p><img src="assets/images/week4_class_path_diagram.png" /></p>
<hr />
</div>
<div id="dfClass" class="section level3" number="4.4.2">
<h3><span class="header-section-number">4.4.2</span> </h3>
<p>Calculate the following quantities for the CFA model shown above.</p>
<ol style="list-style-type: decimal">
<li>The number of parameters in the model.</li>
<li>The pieces of unique information provided by the data.</li>
<li>The number of estimated parameters after applying the necessary scaling constraints.</li>
<li>The degrees of freedom for the estimated model.</li>
</ol>
<details>
<summary>
Click to show the answer
</summary>
<ol style="list-style-type: decimal">
<li>The model contains 88 parameters
<ul>
<li>39 factor loadings</li>
<li>39 residual variances</li>
<li>4 latent variances</li>
<li>6 latent covariances</li>
</ul></li>
<li>Our model will include 39 observed variables, so the data provide 39 (39 + 1) / 2 = 780 pieces of information.</li>
<li>To identify the covariance structure model, we need to fix one parameter in each factor’s sub-model. So, we will
estimate 84 parameters.</li>
<li>The estimated model will have 780 - 84 = 696 degrees of freedom.</li>
</ol>
</details>
<hr />
</div>
<div id="cfaSyntaxClass1" class="section level3" number="4.4.3">
<h3><span class="header-section-number">4.4.3</span> </h3>
<p>Define the <code>lavaan</code> model syntax for the four-factor CFA shown above above.</p>
<ul>
<li>Do not specify any mean structure.</li>
<li>Save this model syntax as an object in your environment.</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="in-class-exercises-3.html#cb166-1" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="st">&#39;</span></span>
<span id="cb166-2"><a href="in-class-exercises-3.html#cb166-2" tabindex="-1"></a><span class="st">warmth     =~ A1 + A2 + A3 + A4 + A5 + A6 + A7 + A8 + A9 + A10</span></span>
<span id="cb166-3"><a href="in-class-exercises-3.html#cb166-3" tabindex="-1"></a><span class="st">liveliness =~ E1 + E2 + E3 + E4 + E5 + E6 + E7 + E8 + E9 + E10</span></span>
<span id="cb166-4"><a href="in-class-exercises-3.html#cb166-4" tabindex="-1"></a><span class="st">vigilance  =~ I1 + I2 + I3 + I4 + I5 + I6 + I7 + I8 + I9 + I10</span></span>
<span id="cb166-5"><a href="in-class-exercises-3.html#cb166-5" tabindex="-1"></a><span class="st">tension    =~ P1 + P2 + P3 + P4 + P5 + P6 + P7 + P8 + P9</span></span>
<span id="cb166-6"><a href="in-class-exercises-3.html#cb166-6" tabindex="-1"></a><span class="st">&#39;</span></span></code></pre></div>
</details>
<hr />
</div>
<div id="cfaEstimationClass1" class="section level3" number="4.4.4">
<h3><span class="header-section-number">4.4.4</span> </h3>
<p>Estimate the CFA model you defined in <a href="in-class-exercises-3.html#cfaSyntaxClass1">4.4.3</a>, and summarize the results.</p>
<ul>
<li>Use the <code>lavaan::cfa()</code> function to estimate the model.</li>
<li>Use the “marker variable method” to set the scale of the latent factors.</li>
<li>Use the default settings for the <code>cfa()</code> function.</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="in-class-exercises-3.html#cb167-1" tabindex="-1"></a><span class="do">## Load the lavaan package:</span></span>
<span id="cb167-2"><a href="in-class-exercises-3.html#cb167-2" tabindex="-1"></a><span class="fu">library</span>(lavaan)</span>
<span id="cb167-3"><a href="in-class-exercises-3.html#cb167-3" tabindex="-1"></a></span>
<span id="cb167-4"><a href="in-class-exercises-3.html#cb167-4" tabindex="-1"></a><span class="do">## Estimate the CFA model:</span></span>
<span id="cb167-5"><a href="in-class-exercises-3.html#cb167-5" tabindex="-1"></a>outC1<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">cfa</span>(mod1, <span class="at">data =</span> cattell)</span>
<span id="cb167-6"><a href="in-class-exercises-3.html#cb167-6" tabindex="-1"></a></span>
<span id="cb167-7"><a href="in-class-exercises-3.html#cb167-7" tabindex="-1"></a><span class="do">## Summarize the fitted model:</span></span>
<span id="cb167-8"><a href="in-class-exercises-3.html#cb167-8" tabindex="-1"></a><span class="fu">summary</span>(outC1<span class="fl">.1</span>)</span></code></pre></div>
<pre><code>## lavaan 0.7-2 ended normally after 42 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        84
## 
##   Number of observations                          1000
## 
## Model Test User Model:
##                                                       
##   Test statistic                              4238.359
##   Degrees of freedom                               696
##   P-value (Chi-square)                           0.000
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   warmth =~                                           
##     A1                1.000                           
##     A2                0.962    0.050   19.056    0.000
##     A3                0.772    0.053   14.567    0.000
##     A4                0.790    0.050   15.654    0.000
##     A5                0.927    0.050   18.449    0.000
##     A6                0.847    0.049   17.261    0.000
##     A7                0.792    0.049   16.257    0.000
##     A8               -0.534    0.059   -9.127    0.000
##     A9               -0.902    0.055  -16.552    0.000
##     A10              -0.431    0.053   -8.068    0.000
##   liveliness =~                                       
##     E1                1.000                           
##     E2                1.273    0.055   23.226    0.000
##     E3                0.488    0.042   11.713    0.000
##     E4                1.166    0.052   22.405    0.000
##     E5                0.342    0.035    9.696    0.000
##     E6                0.783    0.050   15.667    0.000
##     E7               -0.140    0.044   -3.172    0.002
##     E8               -1.027    0.052  -19.799    0.000
##     E9               -0.196    0.042   -4.642    0.000
##     E10              -0.528    0.048  -10.944    0.000
##   vigilance =~                                        
##     I1                1.000                           
##     I2                1.252    0.092   13.589    0.000
##     I3                0.915    0.079   11.629    0.000
##     I4                1.585    0.105   15.059    0.000
##     I5                0.769    0.077    9.997    0.000
##     I6                1.153    0.089   12.972    0.000
##     I7               -1.220    0.087  -13.986    0.000
##     I8               -1.466    0.099  -14.748    0.000
##     I9               -1.219    0.085  -14.295    0.000
##     I10              -1.089    0.085  -12.835    0.000
##   tension =~                                          
##     P1                1.000                           
##     P2                0.908    0.035   25.697    0.000
##     P3                0.577    0.036   15.960    0.000
##     P4                0.582    0.035   16.780    0.000
##     P5                0.361    0.031   11.730    0.000
##     P6                0.449    0.036   12.619    0.000
##     P7                0.425    0.038   11.271    0.000
##     P8               -0.747    0.034  -21.836    0.000
##     P9               -0.370    0.034  -10.964    0.000
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   warmth ~~                                           
##     liveliness        0.245    0.025    9.690    0.000
##     vigilance        -0.207    0.021   -9.902    0.000
##     tension          -0.241    0.028   -8.641    0.000
##   liveliness ~~                                       
##     vigilance        -0.112    0.019   -6.000    0.000
##     tension          -0.030    0.031   -0.966    0.334
##   vigilance ~~                                        
##     tension           0.305    0.029   10.440    0.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .A1                0.594    0.030   19.593    0.000
##    .A2                0.391    0.021   18.471    0.000
##    .A3                0.711    0.034   20.991    0.000
##    .A4                0.592    0.029   20.632    0.000
##    .A5                0.427    0.022   19.052    0.000
##    .A6                0.475    0.024   19.884    0.000
##    .A7                0.521    0.026   20.388    0.000
##    .A8                1.153    0.053   21.957    0.000
##    .A9                0.634    0.031   20.254    0.000
##    .A10               0.992    0.045   22.056    0.000
##    .E1                0.693    0.037   18.840    0.000
##    .E2                0.562    0.037   15.277    0.000
##    .E3                0.890    0.041   21.722    0.000
##    .E4                0.605    0.036   16.826    0.000
##    .E5                0.681    0.031   21.950    0.000
##    .E6                1.075    0.051   20.990    0.000
##    .E7                1.194    0.053   22.321    0.000
##    .E8                0.850    0.044   19.343    0.000
##    .E9                1.076    0.048   22.275    0.000
##    .E10               1.225    0.056   21.817    0.000
##    .I1                0.981    0.046   21.501    0.000
##    .I2                0.702    0.034   20.470    0.000
##    .I3                0.818    0.038   21.498    0.000
##    .I4                0.440    0.025   17.497    0.000
##    .I5                0.991    0.045   21.858    0.000
##    .I6                0.784    0.037   20.927    0.000
##    .I7                0.546    0.027   20.046    0.000
##    .I8                0.488    0.026   18.611    0.000
##    .I9                0.457    0.023   19.598    0.000
##    .I10               0.739    0.035   21.005    0.000
##    .P1                0.392    0.029   13.380    0.000
##    .P2                0.596    0.034   17.379    0.000
##    .P3                0.958    0.045   21.160    0.000
##    .P4                0.864    0.041   21.002    0.000
##    .P5                0.758    0.035   21.769    0.000
##    .P6                0.994    0.046   21.665    0.000
##    .P7                1.145    0.052   21.819    0.000
##    .P8                0.706    0.036   19.578    0.000
##    .P9                0.919    0.042   21.850    0.000
##     warmth            0.453    0.041   10.987    0.000
##     liveliness        0.710    0.058   12.236    0.000
##     vigilance         0.301    0.039    7.720    0.000
##     tension           1.007    0.064   15.610    0.000</code></pre>
</details>
<hr />
</div>
<div id="section-57" class="section level3" number="4.4.5">
<h3><span class="header-section-number">4.4.5</span> </h3>
<p>Do the number of model parameters and degrees of freedom reported in the lavaan output agree with the values you
calculated in <a href="in-class-exercises-3.html#dfClass">4.4.2</a>?</p>
<details>
<summary>
Click to show answer
</summary>
<p>Yes, the values should agree. This first part of the lavaan model summary reports the number of model parameters and the
degrees of freedom.</p>
<pre><code>## lavaan 0.7-2 ended normally after 42 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        84
## 
##   Number of observations                          1000
## 
## Model Test User Model:
##                                                       
##   Test statistic                              4238.359
##   Degrees of freedom                               696
##   P-value (Chi-square)                           0.000</code></pre>
<p>In this case, we see that we’ve estimated 84 parameters and we have df = 696.</p>
</details>
<hr />
</div>
<div id="section-58" class="section level3" number="4.4.6">
<h3><span class="header-section-number">4.4.6</span> </h3>
<p>Examine the factor loadings from the model you estimated in <a href="in-class-exercises-3.html#cfaEstimationClass1">4.4.4</a>, and answer the following
questions.</p>
<ul>
<li>Some of the estimated factor loadings are negative. Why are these particular loadings negative?</li>
<li>Do you think the negative factor loadings are a problem? Explain you reasoning.</li>
<li>Do the estimates make sense given the wording of the observed items and the putative meanings of the latent
constructs?</li>
</ul>
<details>
<summary>
Click to show answer
</summary>
<ul>
<li>The negative factor loadings are associated with reverse-coded items. Such items get negative factor loadings because
higher scores on those items reflect lower levels of the latent construct. In other words, reverse coded items have
negative item-scale correlations.
<span class="math inline">\(\\[3pt]\)</span></li>
<li>No, the negative factor loadings are not inherently problematic. Negative factor loadings do not have a deleterious
effect on the definition of the latent factor. That being said, negative factor loadings can complicate the analysis.
<ul>
<li>Trying to set the scale by fixing the factor loading for a reverse coded item can cause estimation problems or
flip the meaning of the latent factor.</li>
<li>We need to be extra careful when placing constraints for hypothesis testing.
<span class="math inline">\(\\[3pt]\)</span></li>
</ul></li>
<li>Yes, the estimated factor loadings largely align with theoretical expectations. For example, the observed items that
appear to reflect interpersonal “warmth” are associated with positive factor loadings for the <em>Warmth</em> factor, and the
reverse coded items that seem to indicate “coldness” have negative factor loadings. The same pattern holds for all four
latent factors.</li>
</ul>
</details>
<hr />
</div>
<div id="section-59" class="section level3" number="4.4.7">
<h3><span class="header-section-number">4.4.7</span> </h3>
<p>Interpret the latent covariances from the model you estimated in <a href="in-class-exercises-3.html#cfaEstimationClass1">4.4.4</a>.</p>
<ul>
<li>Use the parameter estimates and statistical tests from your model to support your interpretations.</li>
<li>Do the estimates make sense given the putative meanings of the latent constructs?</li>
</ul>
<details>
<summary>
Click to show answer
</summary>
<p>The estimated latent covariances largely conform to theoretical expectations. The two “pro-social” factors, <em>Warmth</em> and
<em>Liveliness</em>, are positively associated
<span class="math inline">\((\psi_{2,1} = 0.245\)</span>,
<span class="math inline">\(\textit{SE} = 0.025\)</span>,
<span class="math inline">\(p &lt; 0.001)\)</span>,
as are the two “anti-social” factors, <em>Vigilance</em> and <em>Tension</em>,
<span class="math inline">\((\psi_{4,3} = 0.305\)</span>,
<span class="math inline">\(\textit{SE} = 0.029\)</span>,
<span class="math inline">\(p &lt; 0.001)\)</span>.
Furthermore, <em>Warmth</em> negatively correlates with both of the “anti-social” factors
(<em>Vigilance</em>: <span class="math inline">\(\psi_{3,1} = -0.207\)</span>,
<span class="math inline">\(\textit{SE} = 0.021\)</span>,
<span class="math inline">\(p &lt; 0.001\)</span>;
<em>Tension</em>: <span class="math inline">\(\psi_{4,1} = -0.241\)</span>,
<span class="math inline">\(\textit{SE} = 0.028\)</span>,
<span class="math inline">\(p &lt; 0.001)\)</span>,
and <em>Liveliness</em> negatively correlates with <em>Vigilance</em>
<span class="math inline">\((\psi_{2,3} = -0.112\)</span>,
<span class="math inline">\(\textit{SE} = 0.019\)</span>,
<span class="math inline">\(p &lt; 0.001)\)</span>.
Only <em>Liveliness</em> and <em>Tension</em> are not significantly associated
<span class="math inline">\((\psi_{2,4} = -0.03\)</span>,
<span class="math inline">\(\textit{SE} = 0.031\)</span>,
<span class="math inline">\(p = 0.334)\)</span>.</p>
</details>
<hr />
<p>We can request more information when we summarize a fitted lavaan model by adding additional arguments to the
<code>summary()</code> call. For the purposes of this course, the following options are most useful.</p>
<ul>
<li><code>ci = TRUE</code>: Include confidence intervals for the estimated parameters</li>
<li><code>stadardized = TRUE</code>: Include the standardized parameter estimates</li>
<li><code>rsquare = TRUE</code>: Include the <span class="math inline">\(R^2\)</span> estimates for all endogenous variables in the model</li>
<li><code>fit.measures = TRUE</code>: Include the model fit statistics</li>
<li><code>modindices = TRUE</code>: Include the modification indices</li>
</ul>
<p>For example, the following code prints the summary including 95% confidence intervals for the parameter estimates.</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="in-class-exercises-3.html#cb170-1" tabindex="-1"></a><span class="fu">summary</span>(outC1<span class="fl">.1</span>, <span class="at">ci =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## lavaan 0.7-2 ended normally after 42 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        84
## 
##   Number of observations                          1000
## 
## Model Test User Model:
##                                                       
##   Test statistic                              4238.359
##   Degrees of freedom                               696
##   P-value (Chi-square)                           0.000
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|) ci.lower ci.upper
##   warmth =~                                                             
##     A1                1.000                               1.000    1.000
##     A2                0.962    0.050   19.056    0.000    0.863    1.060
##     A3                0.772    0.053   14.567    0.000    0.668    0.875
##     A4                0.790    0.050   15.654    0.000    0.691    0.889
##     A5                0.927    0.050   18.449    0.000    0.829    1.026
##     A6                0.847    0.049   17.261    0.000    0.750    0.943
##     A7                0.792    0.049   16.257    0.000    0.696    0.887
##     A8               -0.534    0.059   -9.127    0.000   -0.649   -0.419
##     A9               -0.902    0.055  -16.552    0.000   -1.009   -0.796
##     A10              -0.431    0.053   -8.068    0.000   -0.535   -0.326
##   liveliness =~                                                         
##     E1                1.000                               1.000    1.000
##     E2                1.273    0.055   23.226    0.000    1.166    1.380
##     E3                0.488    0.042   11.713    0.000    0.406    0.569
##     E4                1.166    0.052   22.405    0.000    1.064    1.267
##     E5                0.342    0.035    9.696    0.000    0.273    0.412
##     E6                0.783    0.050   15.667    0.000    0.685    0.881
##     E7               -0.140    0.044   -3.172    0.002   -0.227   -0.054
##     E8               -1.027    0.052  -19.799    0.000   -1.129   -0.926
##     E9               -0.196    0.042   -4.642    0.000   -0.279   -0.113
##     E10              -0.528    0.048  -10.944    0.000   -0.622   -0.433
##   vigilance =~                                                          
##     I1                1.000                               1.000    1.000
##     I2                1.252    0.092   13.589    0.000    1.072    1.433
##     I3                0.915    0.079   11.629    0.000    0.760    1.069
##     I4                1.585    0.105   15.059    0.000    1.378    1.791
##     I5                0.769    0.077    9.997    0.000    0.618    0.920
##     I6                1.153    0.089   12.972    0.000    0.979    1.328
##     I7               -1.220    0.087  -13.986    0.000   -1.392   -1.049
##     I8               -1.466    0.099  -14.748    0.000   -1.661   -1.271
##     I9               -1.219    0.085  -14.295    0.000   -1.387   -1.052
##     I10              -1.089    0.085  -12.835    0.000   -1.255   -0.923
##   tension =~                                                            
##     P1                1.000                               1.000    1.000
##     P2                0.908    0.035   25.697    0.000    0.838    0.977
##     P3                0.577    0.036   15.960    0.000    0.506    0.648
##     P4                0.582    0.035   16.780    0.000    0.514    0.650
##     P5                0.361    0.031   11.730    0.000    0.301    0.422
##     P6                0.449    0.036   12.619    0.000    0.379    0.518
##     P7                0.425    0.038   11.271    0.000    0.351    0.499
##     P8               -0.747    0.034  -21.836    0.000   -0.815   -0.680
##     P9               -0.370    0.034  -10.964    0.000   -0.436   -0.304
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|) ci.lower ci.upper
##   warmth ~~                                                             
##     liveliness        0.245    0.025    9.690    0.000    0.196    0.295
##     vigilance        -0.207    0.021   -9.902    0.000   -0.248   -0.166
##     tension          -0.241    0.028   -8.641    0.000   -0.296   -0.187
##   liveliness ~~                                                         
##     vigilance        -0.112    0.019   -6.000    0.000   -0.149   -0.076
##     tension          -0.030    0.031   -0.966    0.334   -0.091    0.031
##   vigilance ~~                                                          
##     tension           0.305    0.029   10.440    0.000    0.248    0.362
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|) ci.lower ci.upper
##    .A1                0.594    0.030   19.593    0.000    0.534    0.653
##    .A2                0.391    0.021   18.471    0.000    0.350    0.433
##    .A3                0.711    0.034   20.991    0.000    0.645    0.778
##    .A4                0.592    0.029   20.632    0.000    0.536    0.648
##    .A5                0.427    0.022   19.052    0.000    0.383    0.471
##    .A6                0.475    0.024   19.884    0.000    0.428    0.522
##    .A7                0.521    0.026   20.388    0.000    0.471    0.571
##    .A8                1.153    0.053   21.957    0.000    1.050    1.256
##    .A9                0.634    0.031   20.254    0.000    0.573    0.695
##    .A10               0.992    0.045   22.056    0.000    0.904    1.080
##    .E1                0.693    0.037   18.840    0.000    0.621    0.765
##    .E2                0.562    0.037   15.277    0.000    0.490    0.634
##    .E3                0.890    0.041   21.722    0.000    0.809    0.970
##    .E4                0.605    0.036   16.826    0.000    0.535    0.676
##    .E5                0.681    0.031   21.950    0.000    0.620    0.742
##    .E6                1.075    0.051   20.990    0.000    0.975    1.176
##    .E7                1.194    0.053   22.321    0.000    1.089    1.299
##    .E8                0.850    0.044   19.343    0.000    0.764    0.936
##    .E9                1.076    0.048   22.275    0.000    0.981    1.171
##    .E10               1.225    0.056   21.817    0.000    1.115    1.335
##    .I1                0.981    0.046   21.501    0.000    0.892    1.070
##    .I2                0.702    0.034   20.470    0.000    0.635    0.770
##    .I3                0.818    0.038   21.498    0.000    0.743    0.893
##    .I4                0.440    0.025   17.497    0.000    0.391    0.489
##    .I5                0.991    0.045   21.858    0.000    0.902    1.080
##    .I6                0.784    0.037   20.927    0.000    0.711    0.858
##    .I7                0.546    0.027   20.046    0.000    0.492    0.599
##    .I8                0.488    0.026   18.611    0.000    0.437    0.539
##    .I9                0.457    0.023   19.598    0.000    0.411    0.503
##    .I10               0.739    0.035   21.005    0.000    0.670    0.808
##    .P1                0.392    0.029   13.380    0.000    0.335    0.450
##    .P2                0.596    0.034   17.379    0.000    0.529    0.664
##    .P3                0.958    0.045   21.160    0.000    0.869    1.047
##    .P4                0.864    0.041   21.002    0.000    0.784    0.945
##    .P5                0.758    0.035   21.769    0.000    0.690    0.827
##    .P6                0.994    0.046   21.665    0.000    0.904    1.084
##    .P7                1.145    0.052   21.819    0.000    1.042    1.248
##    .P8                0.706    0.036   19.578    0.000    0.635    0.777
##    .P9                0.919    0.042   21.850    0.000    0.836    1.001
##     warmth            0.453    0.041   10.987    0.000    0.372    0.534
##     liveliness        0.710    0.058   12.236    0.000    0.596    0.824
##     vigilance         0.301    0.039    7.720    0.000    0.224    0.377
##     tension           1.007    0.064   15.610    0.000    0.880    1.133</code></pre>
<hr />
</div>
<div id="section-60" class="section level3" number="4.4.8">
<h3><span class="header-section-number">4.4.8</span> </h3>
<p>Summarize the model you estimated in <a href="in-class-exercises-3.html#cfaEstimationClass1">4.4.4</a>, and include the standardized parameter estimates and
the <span class="math inline">\(R^2\)</span> values in the summary.</p>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="in-class-exercises-3.html#cb172-1" tabindex="-1"></a><span class="fu">summary</span>(outC1<span class="fl">.1</span>, <span class="at">standardized =</span> <span class="cn">TRUE</span>, <span class="at">rsquare =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## lavaan 0.7-2 ended normally after 42 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        84
## 
##   Number of observations                          1000
## 
## Model Test User Model:
##                                                       
##   Test statistic                              4238.359
##   Degrees of freedom                               696
##   P-value (Chi-square)                           0.000
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   warmth =~                                                             
##     A1                1.000                               0.673    0.658
##     A2                0.962    0.050   19.056    0.000    0.647    0.719
##     A3                0.772    0.053   14.567    0.000    0.519    0.524
##     A4                0.790    0.050   15.654    0.000    0.532    0.569
##     A5                0.927    0.050   18.449    0.000    0.624    0.690
##     A6                0.847    0.049   17.261    0.000    0.570    0.637
##     A7                0.792    0.049   16.257    0.000    0.533    0.594
##     A8               -0.534    0.059   -9.127    0.000   -0.359   -0.317
##     A9               -0.902    0.055  -16.552    0.000   -0.607   -0.606
##     A10              -0.431    0.053   -8.068    0.000   -0.290   -0.279
##   liveliness =~                                                         
##     E1                1.000                               0.843    0.712
##     E2                1.273    0.055   23.226    0.000    1.073    0.820
##     E3                0.488    0.042   11.713    0.000    0.411    0.399
##     E4                1.166    0.052   22.405    0.000    0.982    0.784
##     E5                0.342    0.035    9.696    0.000    0.288    0.330
##     E6                0.783    0.050   15.667    0.000    0.660    0.537
##     E7               -0.140    0.044   -3.172    0.002   -0.118   -0.108
##     E8               -1.027    0.052  -19.799    0.000   -0.866   -0.685
##     E9               -0.196    0.042   -4.642    0.000   -0.165   -0.158
##     E10              -0.528    0.048  -10.944    0.000   -0.445   -0.373
##   vigilance =~                                                          
##     I1                1.000                               0.548    0.484
##     I2                1.252    0.092   13.589    0.000    0.687    0.634
##     I3                0.915    0.079   11.629    0.000    0.502    0.485
##     I4                1.585    0.105   15.059    0.000    0.869    0.795
##     I5                0.769    0.077    9.997    0.000    0.422    0.390
##     I6                1.153    0.089   12.972    0.000    0.633    0.581
##     I7               -1.220    0.087  -13.986    0.000   -0.669   -0.671
##     I8               -1.466    0.099  -14.748    0.000   -0.804   -0.755
##     I9               -1.219    0.085  -14.295    0.000   -0.669   -0.703
##     I10              -1.089    0.085  -12.835    0.000   -0.597   -0.570
##   tension =~                                                            
##     P1                1.000                               1.003    0.848
##     P2                0.908    0.035   25.697    0.000    0.911    0.763
##     P3                0.577    0.036   15.960    0.000    0.579    0.509
##     P4                0.582    0.035   16.780    0.000    0.584    0.532
##     P5                0.361    0.031   11.730    0.000    0.363    0.384
##     P6                0.449    0.036   12.619    0.000    0.450    0.411
##     P7                0.425    0.038   11.271    0.000    0.427    0.370
##     P8               -0.747    0.034  -21.836    0.000   -0.750   -0.666
##     P9               -0.370    0.034  -10.964    0.000   -0.371   -0.361
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   warmth ~~                                                             
##     liveliness        0.245    0.025    9.690    0.000    0.433    0.433
##     vigilance        -0.207    0.021   -9.902    0.000   -0.560   -0.560
##     tension          -0.241    0.028   -8.641    0.000   -0.358   -0.358
##   liveliness ~~                                                         
##     vigilance        -0.112    0.019   -6.000    0.000   -0.243   -0.243
##     tension          -0.030    0.031   -0.966    0.334   -0.035   -0.035
##   vigilance ~~                                                          
##     tension           0.305    0.029   10.440    0.000    0.554    0.554
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .A1                0.594    0.030   19.593    0.000    0.594    0.567
##    .A2                0.391    0.021   18.471    0.000    0.391    0.483
##    .A3                0.711    0.034   20.991    0.000    0.711    0.725
##    .A4                0.592    0.029   20.632    0.000    0.592    0.677
##    .A5                0.427    0.022   19.052    0.000    0.427    0.523
##    .A6                0.475    0.024   19.884    0.000    0.475    0.594
##    .A7                0.521    0.026   20.388    0.000    0.521    0.647
##    .A8                1.153    0.053   21.957    0.000    1.153    0.899
##    .A9                0.634    0.031   20.254    0.000    0.634    0.632
##    .A10               0.992    0.045   22.056    0.000    0.992    0.922
##    .E1                0.693    0.037   18.840    0.000    0.693    0.494
##    .E2                0.562    0.037   15.277    0.000    0.562    0.328
##    .E3                0.890    0.041   21.722    0.000    0.890    0.840
##    .E4                0.605    0.036   16.826    0.000    0.605    0.386
##    .E5                0.681    0.031   21.950    0.000    0.681    0.891
##    .E6                1.075    0.051   20.990    0.000    1.075    0.712
##    .E7                1.194    0.053   22.321    0.000    1.194    0.988
##    .E8                0.850    0.044   19.343    0.000    0.850    0.531
##    .E9                1.076    0.048   22.275    0.000    1.076    0.975
##    .E10               1.225    0.056   21.817    0.000    1.225    0.861
##    .I1                0.981    0.046   21.501    0.000    0.981    0.765
##    .I2                0.702    0.034   20.470    0.000    0.702    0.598
##    .I3                0.818    0.038   21.498    0.000    0.818    0.765
##    .I4                0.440    0.025   17.497    0.000    0.440    0.368
##    .I5                0.991    0.045   21.858    0.000    0.991    0.848
##    .I6                0.784    0.037   20.927    0.000    0.784    0.662
##    .I7                0.546    0.027   20.046    0.000    0.546    0.549
##    .I8                0.488    0.026   18.611    0.000    0.488    0.430
##    .I9                0.457    0.023   19.598    0.000    0.457    0.505
##    .I10               0.739    0.035   21.005    0.000    0.739    0.675
##    .P1                0.392    0.029   13.380    0.000    0.392    0.280
##    .P2                0.596    0.034   17.379    0.000    0.596    0.418
##    .P3                0.958    0.045   21.160    0.000    0.958    0.741
##    .P4                0.864    0.041   21.002    0.000    0.864    0.717
##    .P5                0.758    0.035   21.769    0.000    0.758    0.852
##    .P6                0.994    0.046   21.665    0.000    0.994    0.831
##    .P7                1.145    0.052   21.819    0.000    1.145    0.863
##    .P8                0.706    0.036   19.578    0.000    0.706    0.557
##    .P9                0.919    0.042   21.850    0.000    0.919    0.870
##     warmth            0.453    0.041   10.987    0.000    1.000    1.000
##     liveliness        0.710    0.058   12.236    0.000    1.000    1.000
##     vigilance         0.301    0.039    7.720    0.000    1.000    1.000
##     tension           1.007    0.064   15.610    0.000    1.000    1.000
## 
## R-Square:
##                    Estimate
##     A1                0.433
##     A2                0.517
##     A3                0.275
##     A4                0.323
##     A5                0.477
##     A6                0.406
##     A7                0.353
##     A8                0.101
##     A9                0.368
##     A10               0.078
##     E1                0.506
##     E2                0.672
##     E3                0.160
##     E4                0.614
##     E5                0.109
##     E6                0.288
##     E7                0.012
##     E8                0.469
##     E9                0.025
##     E10               0.139
##     I1                0.235
##     I2                0.402
##     I3                0.235
##     I4                0.632
##     I5                0.152
##     I6                0.338
##     I7                0.451
##     I8                0.570
##     I9                0.495
##     I10               0.325
##     P1                0.720
##     P2                0.582
##     P3                0.259
##     P4                0.283
##     P5                0.148
##     P6                0.169
##     P7                0.137
##     P8                0.443
##     P9                0.130</code></pre>
</details>
<hr />
<p>We can extract specific elements from the fitted lavaan object with the <code>lavInspect()</code> function. For example, the
following code extracts the number of estimated parameters.</p>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb174-1"><a href="in-class-exercises-3.html#cb174-1" tabindex="-1"></a><span class="fu">lavInspect</span>(outC1<span class="fl">.1</span>, <span class="st">&quot;npar&quot;</span>)</span></code></pre></div>
<pre><code>## [1] 84</code></pre>
<hr />
</div>
<div id="section-61" class="section level3" number="4.4.9">
<h3><span class="header-section-number">4.4.9</span> </h3>
<p>Check the help file for the <code>lavInspect()</code> function to see what you can extract from a fitted lavaan object.</p>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb176-1"><a href="in-class-exercises-3.html#cb176-1" tabindex="-1"></a>?lavInspect</span></code></pre></div>
</details>
<hr />
</div>
<div id="section-62" class="section level3" number="4.4.10">
<h3><span class="header-section-number">4.4.10</span> </h3>
<p>Use the <code>lavInspect()</code> function to extract the following data from the lavaan object you created in
<a href="in-class-exercises-3.html#cfaEstimationClass1">4.4.4</a>.</p>
<ul>
<li>The factor loading matrix</li>
<li>The latent covariance matrix</li>
<li>The estimated <span class="math inline">\(R^2\)</span> values for the indicator variables.</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb177-1"><a href="in-class-exercises-3.html#cb177-1" tabindex="-1"></a><span class="co"># Extract the estimated parameter matrices</span></span>
<span id="cb177-2"><a href="in-class-exercises-3.html#cb177-2" tabindex="-1"></a>parEst <span class="ot">&lt;-</span> <span class="fu">lavInspect</span>(outC1<span class="fl">.1</span>, <span class="st">&quot;estimates&quot;</span>)</span>
<span id="cb177-3"><a href="in-class-exercises-3.html#cb177-3" tabindex="-1"></a></span>
<span id="cb177-4"><a href="in-class-exercises-3.html#cb177-4" tabindex="-1"></a><span class="co"># Print the estimated factor loading matrix</span></span>
<span id="cb177-5"><a href="in-class-exercises-3.html#cb177-5" tabindex="-1"></a>parEst<span class="sc">$</span>lambda</span></code></pre></div>
<pre><code>##     warmth lvlnss viglnc tensin
## A1   1.000  0.000  0.000  0.000
## A2   0.962  0.000  0.000  0.000
## A3   0.772  0.000  0.000  0.000
## A4   0.790  0.000  0.000  0.000
## A5   0.927  0.000  0.000  0.000
## A6   0.847  0.000  0.000  0.000
## A7   0.792  0.000  0.000  0.000
## A8  -0.534  0.000  0.000  0.000
## A9  -0.902  0.000  0.000  0.000
## A10 -0.431  0.000  0.000  0.000
## E1   0.000  1.000  0.000  0.000
## E2   0.000  1.273  0.000  0.000
## E3   0.000  0.488  0.000  0.000
## E4   0.000  1.166  0.000  0.000
## E5   0.000  0.342  0.000  0.000
## E6   0.000  0.783  0.000  0.000
## E7   0.000 -0.140  0.000  0.000
## E8   0.000 -1.027  0.000  0.000
## E9   0.000 -0.196  0.000  0.000
## E10  0.000 -0.528  0.000  0.000
## I1   0.000  0.000  1.000  0.000
## I2   0.000  0.000  1.252  0.000
## I3   0.000  0.000  0.915  0.000
## I4   0.000  0.000  1.585  0.000
## I5   0.000  0.000  0.769  0.000
## I6   0.000  0.000  1.153  0.000
## I7   0.000  0.000 -1.220  0.000
## I8   0.000  0.000 -1.466  0.000
## I9   0.000  0.000 -1.219  0.000
## I10  0.000  0.000 -1.089  0.000
## P1   0.000  0.000  0.000  1.000
## P2   0.000  0.000  0.000  0.908
## P3   0.000  0.000  0.000  0.577
## P4   0.000  0.000  0.000  0.582
## P5   0.000  0.000  0.000  0.361
## P6   0.000  0.000  0.000  0.449
## P7   0.000  0.000  0.000  0.425
## P8   0.000  0.000  0.000 -0.747
## P9   0.000  0.000  0.000 -0.370</code></pre>
<div class="sourceCode" id="cb179"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb179-1"><a href="in-class-exercises-3.html#cb179-1" tabindex="-1"></a><span class="co"># Print the estimated latent covariance matrix</span></span>
<span id="cb179-2"><a href="in-class-exercises-3.html#cb179-2" tabindex="-1"></a>parEst<span class="sc">$</span>psi</span></code></pre></div>
<pre><code>##            warmth lvlnss viglnc tensin
## warmth      0.453                     
## liveliness  0.245  0.710              
## vigilance  -0.207 -0.112  0.301       
## tension    -0.241 -0.030  0.305  1.007</code></pre>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb181-1"><a href="in-class-exercises-3.html#cb181-1" tabindex="-1"></a><span class="co"># Alternatively, we can directly extract the latent covariance matrix</span></span>
<span id="cb181-2"><a href="in-class-exercises-3.html#cb181-2" tabindex="-1"></a><span class="fu">lavInspect</span>(outC1<span class="fl">.1</span>, <span class="st">&quot;cov.lv&quot;</span>)</span></code></pre></div>
<pre><code>##            warmth lvlnss viglnc tensin
## warmth      0.453                     
## liveliness  0.245  0.710              
## vigilance  -0.207 -0.112  0.301       
## tension    -0.241 -0.030  0.305  1.007</code></pre>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb183-1"><a href="in-class-exercises-3.html#cb183-1" tabindex="-1"></a><span class="co"># Extract the estimated R^2 values</span></span>
<span id="cb183-2"><a href="in-class-exercises-3.html#cb183-2" tabindex="-1"></a><span class="fu">lavInspect</span>(outC1<span class="fl">.1</span>, <span class="st">&quot;r2&quot;</span>)</span></code></pre></div>
<pre><code>##    A1    A2    A3    A4    A5    A6    A7    A8    A9   A10    E1    E2    E3 
## 0.433 0.517 0.275 0.323 0.477 0.406 0.353 0.101 0.368 0.078 0.506 0.672 0.160 
##    E4    E5    E6    E7    E8    E9   E10    I1    I2    I3    I4    I5    I6 
## 0.614 0.109 0.288 0.012 0.469 0.025 0.139 0.235 0.402 0.235 0.632 0.152 0.338 
##    I7    I8    I9   I10    P1    P2    P3    P4    P5    P6    P7    P8    P9 
## 0.451 0.570 0.495 0.325 0.720 0.582 0.259 0.283 0.148 0.169 0.137 0.443 0.130</code></pre>
</details>
<hr />
</div>
<div id="cfaEstimationClass2" class="section level3" number="4.4.11">
<h3><span class="header-section-number">4.4.11</span> </h3>
<p>Re-specify the model from <a href="in-class-exercises-3.html#cfaEstimationClass1">4.4.4</a> by fixing all latent covariances to zero.</p>
<ul>
<li>Estimate the re-specified model.</li>
<li>Summarize the fitted model object.</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb185-1"><a href="in-class-exercises-3.html#cb185-1" tabindex="-1"></a><span class="co"># Modify the lavaan model syntax to fix the latent covariances</span></span>
<span id="cb185-2"><a href="in-class-exercises-3.html#cb185-2" tabindex="-1"></a>mod1<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="st">&#39;</span></span>
<span id="cb185-3"><a href="in-class-exercises-3.html#cb185-3" tabindex="-1"></a><span class="st">warmth     =~ A1 + A2 + A3 + A4 + A5 + A6 + A7 + A8 + A9 + A10</span></span>
<span id="cb185-4"><a href="in-class-exercises-3.html#cb185-4" tabindex="-1"></a><span class="st">liveliness =~ E1 + E2 + E3 + E4 + E5 + E6 + E7 + E8 + E9 + E10</span></span>
<span id="cb185-5"><a href="in-class-exercises-3.html#cb185-5" tabindex="-1"></a><span class="st">vigilance  =~ I1 + I2 + I3 + I4 + I5 + I6 + I7 + I8 + I9 + I10</span></span>
<span id="cb185-6"><a href="in-class-exercises-3.html#cb185-6" tabindex="-1"></a><span class="st">tension    =~ P1 + P2 + P3 + P4 + P5 + P6 + P7 + P8 + P9</span></span>
<span id="cb185-7"><a href="in-class-exercises-3.html#cb185-7" tabindex="-1"></a></span>
<span id="cb185-8"><a href="in-class-exercises-3.html#cb185-8" tabindex="-1"></a><span class="st">liveliness ~~ 0*warmth</span></span>
<span id="cb185-9"><a href="in-class-exercises-3.html#cb185-9" tabindex="-1"></a><span class="st">vigilance  ~~ 0*warmth + 0*liveliness</span></span>
<span id="cb185-10"><a href="in-class-exercises-3.html#cb185-10" tabindex="-1"></a><span class="st">tension    ~~ 0*warmth + 0*liveliness + 0*vigilance</span></span>
<span id="cb185-11"><a href="in-class-exercises-3.html#cb185-11" tabindex="-1"></a><span class="st">&#39;</span></span>
<span id="cb185-12"><a href="in-class-exercises-3.html#cb185-12" tabindex="-1"></a></span>
<span id="cb185-13"><a href="in-class-exercises-3.html#cb185-13" tabindex="-1"></a><span class="co"># Estimate the new model</span></span>
<span id="cb185-14"><a href="in-class-exercises-3.html#cb185-14" tabindex="-1"></a>outC1<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">cfa</span>(mod1<span class="fl">.2</span>, <span class="at">data =</span> cattell)</span>
<span id="cb185-15"><a href="in-class-exercises-3.html#cb185-15" tabindex="-1"></a><span class="fu">summary</span>(outC1<span class="fl">.2</span>)</span></code></pre></div>
<pre><code>## lavaan 0.7-2 ended normally after 36 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        78
## 
##   Number of observations                          1000
## 
## Model Test User Model:
##                                                       
##   Test statistic                              4930.129
##   Degrees of freedom                               702
##   P-value (Chi-square)                           0.000
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   warmth =~                                           
##     A1                1.000                           
##     A2                0.908    0.049   18.670    0.000
##     A3                0.796    0.052   15.342    0.000
##     A4                0.786    0.049   15.952    0.000
##     A5                0.893    0.049   18.362    0.000
##     A6                0.831    0.048   17.422    0.000
##     A7                0.783    0.047   16.505    0.000
##     A8               -0.516    0.057   -8.996    0.000
##     A9               -0.860    0.053  -16.269    0.000
##     A10              -0.418    0.052   -7.979    0.000
##   liveliness =~                                       
##     E1                1.000                           
##     E2                1.285    0.056   23.041    0.000
##     E3                0.476    0.042   11.330    0.000
##     E4                1.177    0.053   22.271    0.000
##     E5                0.325    0.036    9.128    0.000
##     E6                0.792    0.051   15.672    0.000
##     E7               -0.129    0.045   -2.887    0.004
##     E8               -1.037    0.053  -19.730    0.000
##     E9               -0.186    0.043   -4.365    0.000
##     E10              -0.541    0.049  -11.115    0.000
##   vigilance =~                                        
##     I1                1.000                           
##     I2                1.308    0.101   12.946    0.000
##     I3                0.939    0.085   11.082    0.000
##     I4                1.669    0.117   14.257    0.000
##     I5                0.789    0.082    9.586    0.000
##     I6                1.188    0.096   12.312    0.000
##     I7               -1.310    0.097  -13.454    0.000
##     I8               -1.556    0.111  -14.036    0.000
##     I9               -1.266    0.094  -13.527    0.000
##     I10              -1.143    0.093  -12.313    0.000
##   tension =~                                          
##     P1                1.000                           
##     P2                0.903    0.035   26.164    0.000
##     P3                0.545    0.036   15.343    0.000
##     P4                0.551    0.034   16.163    0.000
##     P5                0.353    0.030   11.701    0.000
##     P6                0.434    0.035   12.446    0.000
##     P7                0.403    0.037   10.890    0.000
##     P8               -0.734    0.033  -21.961    0.000
##     P9               -0.326    0.033   -9.826    0.000
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   warmth ~~                                           
##     liveliness        0.000                           
##     vigilance         0.000                           
##   liveliness ~~                                       
##     vigilance         0.000                           
##   warmth ~~                                           
##     tension           0.000                           
##   liveliness ~~                                       
##     tension           0.000                           
##   vigilance ~~                                        
##     tension           0.000                           
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .A1                0.571    0.030   18.989    0.000
##    .A2                0.419    0.023   18.565    0.000
##    .A3                0.680    0.033   20.572    0.000
##    .A4                0.582    0.029   20.325    0.000
##    .A5                0.438    0.023   18.847    0.000
##    .A6                0.472    0.024   19.548    0.000
##    .A7                0.513    0.026   20.067    0.000
##    .A8                1.156    0.053   21.921    0.000
##    .A9                0.652    0.032   20.182    0.000
##    .A10               0.993    0.045   22.025    0.000
##    .E1                0.700    0.037   18.824    0.000
##    .E2                0.553    0.037   14.893    0.000
##    .E3                0.899    0.041   21.752    0.000
##    .E4                0.597    0.036   16.530    0.000
##    .E5                0.690    0.031   21.992    0.000
##    .E6                1.070    0.051   20.934    0.000
##    .E7                1.197    0.054   22.327    0.000
##    .E8                0.843    0.044   19.214    0.000
##    .E9                1.079    0.048   22.283    0.000
##    .E10               1.217    0.056   21.779    0.000
##    .I1                1.008    0.047   21.535    0.000
##    .I2                0.705    0.035   20.333    0.000
##    .I3                0.828    0.039   21.474    0.000
##    .I4                0.432    0.026   16.914    0.000
##    .I5                0.998    0.046   21.842    0.000
##    .I6                0.798    0.038   20.884    0.000
##    .I7                0.523    0.027   19.608    0.000
##    .I8                0.471    0.026   18.021    0.000
##    .I9                0.465    0.024   19.470    0.000
##    .I10               0.738    0.035   20.884    0.000
##    .P1                0.352    0.030   11.786    0.000
##    .P2                0.571    0.034   16.758    0.000
##    .P3                0.982    0.046   21.266    0.000
##    .P4                0.887    0.042   21.119    0.000
##    .P5                0.759    0.035   21.771    0.000
##    .P6                1.000    0.046   21.685    0.000
##    .P7                1.157    0.053   21.857    0.000
##    .P8                0.704    0.036   19.509    0.000
##    .P9                0.945    0.043   21.957    0.000
##     warmth            0.475    0.042   11.229    0.000
##     liveliness        0.703    0.058   12.125    0.000
##     vigilance         0.274    0.038    7.289    0.000
##     tension           1.047    0.066   15.950    0.000</code></pre>
<p>Alternatively, we can keep the original model string and tell the <code>cfa()</code> function not to estimate any latent
covariances by setting the option <code>orthogonal.x = TRUE</code>.</p>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb187-1"><a href="in-class-exercises-3.html#cb187-1" tabindex="-1"></a>outC1<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">cfa</span>(mod1, <span class="at">data =</span> cattell, <span class="at">orthogonal.x =</span> <span class="cn">TRUE</span>)</span>
<span id="cb187-2"><a href="in-class-exercises-3.html#cb187-2" tabindex="-1"></a><span class="fu">summary</span>(outC1<span class="fl">.2</span>)</span></code></pre></div>
<pre><code>## lavaan 0.7-2 ended normally after 36 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        78
## 
##   Number of observations                          1000
## 
## Model Test User Model:
##                                                       
##   Test statistic                              4930.129
##   Degrees of freedom                               702
##   P-value (Chi-square)                           0.000
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   warmth =~                                           
##     A1                1.000                           
##     A2                0.908    0.049   18.670    0.000
##     A3                0.796    0.052   15.342    0.000
##     A4                0.786    0.049   15.952    0.000
##     A5                0.893    0.049   18.362    0.000
##     A6                0.831    0.048   17.422    0.000
##     A7                0.783    0.047   16.505    0.000
##     A8               -0.516    0.057   -8.996    0.000
##     A9               -0.860    0.053  -16.269    0.000
##     A10              -0.418    0.052   -7.979    0.000
##   liveliness =~                                       
##     E1                1.000                           
##     E2                1.285    0.056   23.041    0.000
##     E3                0.476    0.042   11.330    0.000
##     E4                1.177    0.053   22.271    0.000
##     E5                0.325    0.036    9.128    0.000
##     E6                0.792    0.051   15.672    0.000
##     E7               -0.129    0.045   -2.887    0.004
##     E8               -1.037    0.053  -19.730    0.000
##     E9               -0.186    0.043   -4.365    0.000
##     E10              -0.541    0.049  -11.115    0.000
##   vigilance =~                                        
##     I1                1.000                           
##     I2                1.308    0.101   12.946    0.000
##     I3                0.939    0.085   11.082    0.000
##     I4                1.669    0.117   14.257    0.000
##     I5                0.789    0.082    9.586    0.000
##     I6                1.188    0.096   12.312    0.000
##     I7               -1.310    0.097  -13.454    0.000
##     I8               -1.556    0.111  -14.036    0.000
##     I9               -1.266    0.094  -13.527    0.000
##     I10              -1.143    0.093  -12.313    0.000
##   tension =~                                          
##     P1                1.000                           
##     P2                0.903    0.035   26.164    0.000
##     P3                0.545    0.036   15.343    0.000
##     P4                0.551    0.034   16.163    0.000
##     P5                0.353    0.030   11.701    0.000
##     P6                0.434    0.035   12.446    0.000
##     P7                0.403    0.037   10.890    0.000
##     P8               -0.734    0.033  -21.961    0.000
##     P9               -0.326    0.033   -9.826    0.000
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   warmth ~~                                           
##     liveliness        0.000                           
##     vigilance         0.000                           
##     tension           0.000                           
##   liveliness ~~                                       
##     vigilance         0.000                           
##     tension           0.000                           
##   vigilance ~~                                        
##     tension           0.000                           
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .A1                0.571    0.030   18.989    0.000
##    .A2                0.419    0.023   18.565    0.000
##    .A3                0.680    0.033   20.572    0.000
##    .A4                0.582    0.029   20.325    0.000
##    .A5                0.438    0.023   18.847    0.000
##    .A6                0.472    0.024   19.548    0.000
##    .A7                0.513    0.026   20.067    0.000
##    .A8                1.156    0.053   21.921    0.000
##    .A9                0.652    0.032   20.182    0.000
##    .A10               0.993    0.045   22.025    0.000
##    .E1                0.700    0.037   18.824    0.000
##    .E2                0.553    0.037   14.893    0.000
##    .E3                0.899    0.041   21.752    0.000
##    .E4                0.597    0.036   16.530    0.000
##    .E5                0.690    0.031   21.992    0.000
##    .E6                1.070    0.051   20.934    0.000
##    .E7                1.197    0.054   22.327    0.000
##    .E8                0.843    0.044   19.214    0.000
##    .E9                1.079    0.048   22.283    0.000
##    .E10               1.217    0.056   21.779    0.000
##    .I1                1.008    0.047   21.535    0.000
##    .I2                0.705    0.035   20.333    0.000
##    .I3                0.828    0.039   21.474    0.000
##    .I4                0.432    0.026   16.914    0.000
##    .I5                0.998    0.046   21.842    0.000
##    .I6                0.798    0.038   20.884    0.000
##    .I7                0.523    0.027   19.608    0.000
##    .I8                0.471    0.026   18.021    0.000
##    .I9                0.465    0.024   19.470    0.000
##    .I10               0.738    0.035   20.884    0.000
##    .P1                0.352    0.030   11.786    0.000
##    .P2                0.571    0.034   16.758    0.000
##    .P3                0.982    0.046   21.266    0.000
##    .P4                0.887    0.042   21.119    0.000
##    .P5                0.759    0.035   21.771    0.000
##    .P6                1.000    0.046   21.685    0.000
##    .P7                1.157    0.053   21.857    0.000
##    .P8                0.704    0.036   19.509    0.000
##    .P9                0.945    0.043   21.957    0.000
##     warmth            0.475    0.042   11.229    0.000
##     liveliness        0.703    0.058   12.125    0.000
##     vigilance         0.274    0.038    7.289    0.000
##     tension           1.047    0.066   15.950    0.000</code></pre>
</details>
<hr />
</div>
<div id="section-63" class="section level3" number="4.4.12">
<h3><span class="header-section-number">4.4.12</span> </h3>
<p>Compare the factor loadings for the <em>Warmth</em> construct from the following two models:</p>
<ul>
<li>M1: The correlated-factor model from <a href="in-class-exercises-3.html#cfaEstimationClass1">4.4.4</a></li>
<li>M2: The orthogonal-factor model from <a href="in-class-exercises-3.html#cfaEstimationClass2">4.4.11</a></li>
</ul>
<p>Are the factor loading matrices equal or different across models? What’s going on here? How would you explain the
differences (or lack thereof)?</p>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb189"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb189-1"><a href="in-class-exercises-3.html#cb189-1" tabindex="-1"></a><span class="co"># Factor loadings from the correlated-factor CFA</span></span>
<span id="cb189-2"><a href="in-class-exercises-3.html#cb189-2" tabindex="-1"></a><span class="fu">lavInspect</span>(outC1<span class="fl">.1</span>, <span class="st">&quot;estimates&quot;</span>)<span class="sc">$</span>lambda[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="dv">1</span>, drop <span class="ot">=</span> <span class="cn">FALSE</span>]</span></code></pre></div>
<pre><code>##         warmth
## A1   1.0000000
## A2   0.9615773
## A3   0.7715174
## A4   0.7904305
## A5   0.9271921
## A6   0.8465595
## A7   0.7915340
## A8  -0.5341244
## A9  -0.9023822
## A10 -0.4305772</code></pre>
<div class="sourceCode" id="cb191"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb191-1"><a href="in-class-exercises-3.html#cb191-1" tabindex="-1"></a><span class="co"># Factor loadings from the orthogonal-factor CFA</span></span>
<span id="cb191-2"><a href="in-class-exercises-3.html#cb191-2" tabindex="-1"></a><span class="fu">lavInspect</span>(outC1<span class="fl">.2</span>, <span class="st">&quot;estimates&quot;</span>)<span class="sc">$</span>lambda[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="dv">1</span>, drop <span class="ot">=</span> <span class="cn">FALSE</span>]</span></code></pre></div>
<pre><code>##         warmth
## A1   1.0000000
## A2   0.9076620
## A3   0.7961509
## A4   0.7855184
## A5   0.8931789
## A6   0.8305816
## A7   0.7828006
## A8  -0.5159300
## A9  -0.8597832
## A10 -0.4177278</code></pre>
<details>
<summary>
Click for explanation
</summary>
<p>The models produce slightly different factor loadings because the different latent covariance structures imply subtly
different definitions of the <em>Warmth</em> factor.</p>
<ul>
<li>M1 is the more flexible and “accurate” of the two models.
<ul>
<li>The latent covariance structure of the CFA is fully saturated. So, the estimator has the best possible chance of
fitting the data well (more details on what we mean by “fitting the data” coming next week).</li>
</ul></li>
<li>M2 imposes very strong constraints on the model structure.
<ul>
<li>The model forces independence between the latent constructs. So, M2 “tries” to estimate a <em>Warmth</em> factor that
best conforms to a reality wherein <em>Warmth</em>, <em>Liveliness</em>, <em>Vigilance</em>, and <em>Tension</em> are completely unrelated
concepts.</li>
</ul></li>
</ul>
<p>M1 is the more appropriate way of estimating these four latent factors. M2 places untenable constraints on the latent
covariance structure. These Draconian constraints influence the estimates of other model parameters in ways that we
probably don’t want (unless we have good reason to force an orthogonal definition of these constructs).</p>
</details>
</details>
<hr />
<p>End of In-Class Exercises</p>
<hr />

</div>
</div>
<!-- </div> -->
            </section>

          </div>
        </div>
      </div>
<a href="at-home-exercises-3.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="cfa-ii.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": false,
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section",
    "search": true
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
