<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>2.4 In-Class Exercises | Introduction to Structural Equation Modeling</title>
  <meta name="description" content="2.4 In-Class Exercises | Introduction to Structural Equation Modeling" />
  <meta name="generator" content="bookdown 0.48 and GitBook 2.6.7" />

  <meta property="og:title" content="2.4 In-Class Exercises | Introduction to Structural Equation Modeling" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="2.4 In-Class Exercises | Introduction to Structural Equation Modeling" />
  
  
  

<meta name="author" content="Kyle M. Lang" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="at-home-exercises-1.html"/>
<link rel="next" href="mediation-moderation.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="libs/pagedtable-1.1/js/pagedtable.js"></script>
<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="assets/html/style.css" type="text/css" />
<link rel="stylesheet" href="font-awesome.min.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./index.html">Introduction to SEM</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Course Information</a>
<ul>
<li class="chapter" data-level="" data-path="acknowledgement.html"><a href="acknowledgement.html"><i class="fa fa-check"></i>Acknowledgement</a></li>
<li class="chapter" data-level="" data-path="instructors.html"><a href="instructors.html"><i class="fa fa-check"></i>Instructors</a></li>
<li class="chapter" data-level="" data-path="course-overview.html"><a href="course-overview.html"><i class="fa fa-check"></i>Course overview</a></li>
<li class="chapter" data-level="" data-path="schedule.html"><a href="schedule.html"><i class="fa fa-check"></i>Schedule</a></li>
<li class="chapter" data-level="" data-path="learning-goals.html"><a href="learning-goals.html"><i class="fa fa-check"></i>Learning goals</a>
<ul>
<li class="chapter" data-level="" data-path="learning-goals.html"><a href="learning-goals.html#background"><i class="fa fa-check"></i>Background knowledge</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="resources.html"><a href="resources.html"><i class="fa fa-check"></i>Resources</a>
<ul>
<li class="chapter" data-level="" data-path="resources.html"><a href="resources.html#literature"><i class="fa fa-check"></i>Literature</a></li>
<li class="chapter" data-level="" data-path="resources.html"><a href="resources.html#reading-questions"><i class="fa fa-check"></i>Reading questions</a></li>
<li class="chapter" data-level="" data-path="resources.html"><a href="resources.html#software"><i class="fa fa-check"></i>Software</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="logistics.html"><a href="logistics.html"><i class="fa fa-check"></i>Logistics</a>
<ul>
<li class="chapter" data-level="" data-path="logistics.html"><a href="logistics.html#weekly-preparation"><i class="fa fa-check"></i>Weekly preparation</a></li>
<li class="chapter" data-level="" data-path="logistics.html"><a href="logistics.html#evaluation"><i class="fa fa-check"></i>Evaluation</a></li>
<li class="chapter" data-level="" data-path="logistics.html"><a href="logistics.html#attendance"><i class="fa fa-check"></i>Attendance</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="ai_policy.html"><a href="ai_policy.html"><i class="fa fa-check"></i>Using GenAI</a>
<ul>
<li class="chapter" data-level="" data-path="ai_policy.html"><a href="ai_policy.html#ai-index"><i class="fa fa-check"></i>AI index</a></li>
<li class="chapter" data-level="" data-path="ai_policy.html"><a href="ai_policy.html#acceptable-usage-in-this-course"><i class="fa fa-check"></i>Acceptable usage in this course</a></li>
<li class="chapter" data-level="" data-path="ai_policy.html"><a href="ai_policy.html#including-ai-generated-content-in-your-work"><i class="fa fa-check"></i>Including AI-generated content in your work</a></li>
<li class="chapter" data-level="" data-path="ai_policy.html"><a href="ai_policy.html#referencing-and-academic-integrity"><i class="fa fa-check"></i>Referencing and academic integrity</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="assignments.html"><a href="assignments.html"><i class="fa fa-check"></i>Assignments</a>
<ul>
<li class="chapter" data-level="" data-path="assignment-guidelines.html"><a href="assignment-guidelines.html"><i class="fa fa-check"></i>Assignment Guidelines</a>
<ul>
<li class="chapter" data-level="" data-path="assignment-guidelines.html"><a href="assignment-guidelines.html#a1"><i class="fa fa-check"></i>Assignment 1: Path Analysis</a></li>
<li class="chapter" data-level="" data-path="assignment-guidelines.html"><a href="assignment-guidelines.html#a2"><i class="fa fa-check"></i>Assignment 2: Structural Equation Modeling</a></li>
<li class="chapter" data-level="" data-path="assignment-guidelines.html"><a href="assignment-guidelines.html#data_options"><i class="fa fa-check"></i>Data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="elaboration-tips.html"><a href="elaboration-tips.html"><i class="fa fa-check"></i>Elaboration &amp; Tips</a>
<ul>
<li class="chapter" data-level="" data-path="elaboration-tips.html"><a href="elaboration-tips.html#progression"><i class="fa fa-check"></i>Progression</a></li>
<li class="chapter" data-level="" data-path="elaboration-tips.html"><a href="elaboration-tips.html#rq"><i class="fa fa-check"></i>Theoretical Model &amp; Research Question</a></li>
<li class="chapter" data-level="" data-path="elaboration-tips.html"><a href="elaboration-tips.html#model_assumptions"><i class="fa fa-check"></i>Assumptions</a></li>
<li class="chapter" data-level="" data-path="elaboration-tips.html"><a href="elaboration-tips.html#reporting_standards"><i class="fa fa-check"></i>Reporting Standards</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="procedures.html"><a href="procedures.html"><i class="fa fa-check"></i>Procedures</a>
<ul>
<li class="chapter" data-level="" data-path="procedures.html"><a href="procedures.html#formatting"><i class="fa fa-check"></i>Formatting</a></li>
<li class="chapter" data-level="" data-path="procedures.html"><a href="procedures.html#length"><i class="fa fa-check"></i>Length</a></li>
<li class="chapter" data-level="" data-path="procedures.html"><a href="procedures.html#submission-2"><i class="fa fa-check"></i>Submission</a></li>
<li class="chapter" data-level="" data-path="procedures.html"><a href="procedures.html#rules"><i class="fa fa-check"></i>Rules</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="assignment_grading.html"><a href="assignment_grading.html"><i class="fa fa-check"></i>Grading</a>
<ul>
<li class="chapter" data-level="" data-path="assignment_grading.html"><a href="assignment_grading.html#assignment-1"><i class="fa fa-check"></i>Assignment 1</a></li>
<li class="chapter" data-level="" data-path="assignment_grading.html"><a href="assignment_grading.html#assignment-2"><i class="fa fa-check"></i>Assignment 2</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="software-setup.html"><a href="software-setup.html"><i class="fa fa-check"></i>Software Setup</a>
<ul>
<li class="chapter" data-level="" data-path="typographic-conventions.html"><a href="typographic-conventions.html"><i class="fa fa-check"></i>Typographic Conventions</a></li>
<li class="chapter" data-level="" data-path="installing-software.html"><a href="installing-software.html"><i class="fa fa-check"></i>Installing software</a>
<ul>
<li class="chapter" data-level="" data-path="installing-software.html"><a href="installing-software.html#installing-r"><i class="fa fa-check"></i>Installing R</a></li>
<li class="chapter" data-level="" data-path="installing-software.html"><a href="installing-software.html#installing-rstudio"><i class="fa fa-check"></i>Installing RStudio</a></li>
<li class="chapter" data-level="" data-path="installing-software.html"><a href="installing-software.html#installing-packages"><i class="fa fa-check"></i>Installing packages</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="course-data.html"><a href="course-data.html"><i class="fa fa-check"></i>Course Data</a>
<ul>
<li class="chapter" data-level="" data-path="note-on-data-updates.html"><a href="note-on-data-updates.html"><i class="fa fa-check"></i>Note on Data Updates</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction-to-r.html"><a href="introduction-to-r.html"><i class="fa fa-check"></i><b>1</b> Introduction to R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="lecture.html"><a href="lecture.html"><i class="fa fa-check"></i><b>1.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="lecture.html"><a href="lecture.html#recordings"><i class="fa fa-check"></i><b>1.1.1</b> Recordings</a></li>
<li class="chapter" data-level="1.1.2" data-path="lecture.html"><a href="lecture.html#slides"><i class="fa fa-check"></i><b>1.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="reading.html"><a href="reading.html"><i class="fa fa-check"></i><b>1.2</b> Reading</a></li>
<li class="chapter" data-level="1.3" data-path="at-home-exercises.html"><a href="at-home-exercises.html"><i class="fa fa-check"></i><b>1.3</b> At-Home Exercises</a></li>
<li class="chapter" data-level="1.4" data-path="in-class-exercises.html"><a href="in-class-exercises.html"><i class="fa fa-check"></i><b>1.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="" data-path="in-class-exercises.html"><a href="in-class-exercises.html#recap"><i class="fa fa-check"></i>Recap</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="statistical-modeling-path-analysis.html"><a href="statistical-modeling-path-analysis.html"><i class="fa fa-check"></i><b>2</b> Statistical Modeling &amp; Path Analysis</a>
<ul>
<li class="chapter" data-level="2.1" data-path="lecture-1.html"><a href="lecture-1.html"><i class="fa fa-check"></i><b>2.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="lecture-1.html"><a href="lecture-1.html#recordings-1"><i class="fa fa-check"></i><b>2.1.1</b> Recordings</a></li>
<li class="chapter" data-level="2.1.2" data-path="lecture-1.html"><a href="lecture-1.html#slides-1"><i class="fa fa-check"></i><b>2.1.2</b> Slides</a></li>
<li class="chapter" data-level="2.1.3" data-path="lecture-1.html"><a href="lecture-1.html#materials-from-the-lecture-meeting"><i class="fa fa-check"></i><b>2.1.3</b> Materials from the lecture meeting</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="reading-1.html"><a href="reading-1.html"><i class="fa fa-check"></i><b>2.2</b> Reading</a>
<ul>
<li class="chapter" data-level="" data-path="reading-1.html"><a href="reading-1.html#reference"><i class="fa fa-check"></i>Reference</a></li>
<li class="chapter" data-level="" data-path="reading-1.html"><a href="reading-1.html#questions"><i class="fa fa-check"></i>Questions</a></li>
<li class="chapter" data-level="" data-path="reading-1.html"><a href="reading-1.html#suggested-reading-optional"><i class="fa fa-check"></i>Suggested Reading (Optional)</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html"><i class="fa fa-check"></i><b>2.3</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#setup"><i class="fa fa-check"></i><b>2.3.1</b> Setup</a></li>
<li class="chapter" data-level="2.3.2" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#section"><i class="fa fa-check"></i><b>2.3.2</b> </a></li>
<li class="chapter" data-level="2.3.3" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#section-1"><i class="fa fa-check"></i><b>2.3.3</b> </a></li>
<li class="chapter" data-level="2.3.4" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#slr1"><i class="fa fa-check"></i><b>2.3.4</b> </a></li>
<li class="chapter" data-level="2.3.5" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#slr2"><i class="fa fa-check"></i><b>2.3.5</b> </a></li>
<li class="chapter" data-level="2.3.6" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#slr3"><i class="fa fa-check"></i><b>2.3.6</b> </a></li>
<li class="chapter" data-level="2.3.7" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#mlr"><i class="fa fa-check"></i><b>2.3.7</b> </a></li>
<li class="chapter" data-level="2.3.8" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#section-2"><i class="fa fa-check"></i><b>2.3.8</b> </a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="in-class-exercises-1.html"><a href="in-class-exercises-1.html"><i class="fa fa-check"></i><b>2.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="in-class-exercises-1.html"><a href="in-class-exercises-1.html#setup-1"><i class="fa fa-check"></i><b>2.4.1</b> Setup</a></li>
<li class="chapter" data-level="2.4.2" data-path="in-class-exercises-1.html"><a href="in-class-exercises-1.html#data-exploration"><i class="fa fa-check"></i><b>2.4.2</b> Data Exploration</a></li>
<li class="chapter" data-level="2.4.3" data-path="in-class-exercises-1.html"><a href="in-class-exercises-1.html#linear-modeling"><i class="fa fa-check"></i><b>2.4.3</b> Linear Modeling</a></li>
<li class="chapter" data-level="2.4.4" data-path="in-class-exercises-1.html"><a href="in-class-exercises-1.html#categorical-ivs"><i class="fa fa-check"></i><b>2.4.4</b> Categorical IVs</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="mediation-moderation.html"><a href="mediation-moderation.html"><i class="fa fa-check"></i><b>3</b> Mediation &amp; Moderation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="lecture-2.html"><a href="lecture-2.html"><i class="fa fa-check"></i><b>3.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="lecture-2.html"><a href="lecture-2.html#recordings-2"><i class="fa fa-check"></i><b>3.1.1</b> Recordings</a></li>
<li class="chapter" data-level="3.1.2" data-path="lecture-2.html"><a href="lecture-2.html#slides-2"><i class="fa fa-check"></i><b>3.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="reading-2.html"><a href="reading-2.html"><i class="fa fa-check"></i><b>3.2</b> Reading</a>
<ul>
<li class="chapter" data-level="" data-path="reading-2.html"><a href="reading-2.html#reference-1"><i class="fa fa-check"></i>Reference</a></li>
<li class="chapter" data-level="" data-path="reading-2.html"><a href="reading-2.html#questions-1"><i class="fa fa-check"></i>Questions</a></li>
<li class="chapter" data-level="" data-path="reading-2.html"><a href="reading-2.html#reference-2"><i class="fa fa-check"></i>Reference</a></li>
<li class="chapter" data-level="" data-path="reading-2.html"><a href="reading-2.html#questions-2"><i class="fa fa-check"></i>Questions</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="at-home-exercises-2.html"><a href="at-home-exercises-2.html"><i class="fa fa-check"></i><b>3.3</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="at-home-exercises-2.html"><a href="at-home-exercises-2.html#setup-2"><i class="fa fa-check"></i><b>3.3.1</b> Setup</a></li>
<li class="chapter" data-level="3.3.2" data-path="at-home-exercises-2.html"><a href="at-home-exercises-2.html#mediation"><i class="fa fa-check"></i><b>3.3.2</b> Mediation</a></li>
<li class="chapter" data-level="3.3.3" data-path="at-home-exercises-2.html"><a href="at-home-exercises-2.html#moderation"><i class="fa fa-check"></i><b>3.3.3</b> Moderation</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="in-class-exercises-2.html"><a href="in-class-exercises-2.html"><i class="fa fa-check"></i><b>3.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="in-class-exercises-2.html"><a href="in-class-exercises-2.html#setup-3"><i class="fa fa-check"></i><b>3.4.1</b> Setup</a></li>
<li class="chapter" data-level="3.4.2" data-path="in-class-exercises-2.html"><a href="in-class-exercises-2.html#mediation-1"><i class="fa fa-check"></i><b>3.4.2</b> Mediation</a></li>
<li class="chapter" data-level="3.4.3" data-path="in-class-exercises-2.html"><a href="in-class-exercises-2.html#moderation-1"><i class="fa fa-check"></i><b>3.4.3</b> Moderation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="cfa-i.html"><a href="cfa-i.html"><i class="fa fa-check"></i><b>4</b> CFA I</a>
<ul>
<li class="chapter" data-level="4.1" data-path="lecture-3.html"><a href="lecture-3.html"><i class="fa fa-check"></i><b>4.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="lecture-3.html"><a href="lecture-3.html#recordings-3"><i class="fa fa-check"></i><b>4.1.1</b> Recordings</a></li>
<li class="chapter" data-level="4.1.2" data-path="lecture-3.html"><a href="lecture-3.html#slides-3"><i class="fa fa-check"></i><b>4.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="reading-3.html"><a href="reading-3.html"><i class="fa fa-check"></i><b>4.2</b> Reading</a>
<ul>
<li class="chapter" data-level="" data-path="reading-3.html"><a href="reading-3.html#reference-3"><i class="fa fa-check"></i>Reference</a></li>
<li class="chapter" data-level="" data-path="reading-3.html"><a href="reading-3.html#questions-3"><i class="fa fa-check"></i>Questions</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html"><i class="fa fa-check"></i><b>4.3</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#setup-4"><i class="fa fa-check"></i><b>4.3.1</b> Setup</a></li>
<li class="chapter" data-level="4.3.2" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-45"><i class="fa fa-check"></i><b>4.3.2</b> </a></li>
<li class="chapter" data-level="4.3.3" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-46"><i class="fa fa-check"></i><b>4.3.3</b> </a></li>
<li class="chapter" data-level="4.3.4" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#df"><i class="fa fa-check"></i><b>4.3.4</b> </a></li>
<li class="chapter" data-level="4.3.5" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#cfaSyntax1"><i class="fa fa-check"></i><b>4.3.5</b> </a></li>
<li class="chapter" data-level="4.3.6" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#cfaEstimationHome1"><i class="fa fa-check"></i><b>4.3.6</b> </a></li>
<li class="chapter" data-level="4.3.7" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-47"><i class="fa fa-check"></i><b>4.3.7</b> </a></li>
<li class="chapter" data-level="4.3.8" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-48"><i class="fa fa-check"></i><b>4.3.8</b> </a></li>
<li class="chapter" data-level="4.3.9" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-49"><i class="fa fa-check"></i><b>4.3.9</b> </a></li>
<li class="chapter" data-level="4.3.10" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#cfaSyntax2"><i class="fa fa-check"></i><b>4.3.10</b> </a></li>
<li class="chapter" data-level="4.3.11" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#cfaEstimation2"><i class="fa fa-check"></i><b>4.3.11</b> </a></li>
<li class="chapter" data-level="4.3.12" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-50"><i class="fa fa-check"></i><b>4.3.12</b> </a></li>
<li class="chapter" data-level="4.3.13" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-51"><i class="fa fa-check"></i><b>4.3.13</b> </a></li>
<li class="chapter" data-level="4.3.14" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-52"><i class="fa fa-check"></i><b>4.3.14</b> </a></li>
<li class="chapter" data-level="4.3.15" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#cfaEstimation3"><i class="fa fa-check"></i><b>4.3.15</b> </a></li>
<li class="chapter" data-level="4.3.16" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-53"><i class="fa fa-check"></i><b>4.3.16</b> </a></li>
<li class="chapter" data-level="4.3.17" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-54"><i class="fa fa-check"></i><b>4.3.17</b> </a></li>
<li class="chapter" data-level="4.3.18" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-55"><i class="fa fa-check"></i><b>4.3.18</b> </a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html"><i class="fa fa-check"></i><b>4.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-56"><i class="fa fa-check"></i><b>4.4.1</b> </a></li>
<li class="chapter" data-level="4.4.2" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#dfClass"><i class="fa fa-check"></i><b>4.4.2</b> </a></li>
<li class="chapter" data-level="4.4.3" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#cfaSyntaxClass1"><i class="fa fa-check"></i><b>4.4.3</b> </a></li>
<li class="chapter" data-level="4.4.4" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#cfaEstimationClass1"><i class="fa fa-check"></i><b>4.4.4</b> </a></li>
<li class="chapter" data-level="4.4.5" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-57"><i class="fa fa-check"></i><b>4.4.5</b> </a></li>
<li class="chapter" data-level="4.4.6" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-58"><i class="fa fa-check"></i><b>4.4.6</b> </a></li>
<li class="chapter" data-level="4.4.7" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-59"><i class="fa fa-check"></i><b>4.4.7</b> </a></li>
<li class="chapter" data-level="4.4.8" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-60"><i class="fa fa-check"></i><b>4.4.8</b> </a></li>
<li class="chapter" data-level="4.4.9" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-61"><i class="fa fa-check"></i><b>4.4.9</b> </a></li>
<li class="chapter" data-level="4.4.10" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-62"><i class="fa fa-check"></i><b>4.4.10</b> </a></li>
<li class="chapter" data-level="4.4.11" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#cfaEstimationClass2"><i class="fa fa-check"></i><b>4.4.11</b> </a></li>
<li class="chapter" data-level="4.4.12" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-63"><i class="fa fa-check"></i><b>4.4.12</b> </a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="cfa-ii.html"><a href="cfa-ii.html"><i class="fa fa-check"></i><b>5</b> CFA II</a>
<ul>
<li class="chapter" data-level="5.1" data-path="lecture-4.html"><a href="lecture-4.html"><i class="fa fa-check"></i><b>5.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="lecture-4.html"><a href="lecture-4.html#recordings-4"><i class="fa fa-check"></i><b>5.1.1</b> Recordings</a></li>
<li class="chapter" data-level="5.1.2" data-path="lecture-4.html"><a href="lecture-4.html#slides-4"><i class="fa fa-check"></i><b>5.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="reading-4.html"><a href="reading-4.html"><i class="fa fa-check"></i><b>5.2</b> Reading</a>
<ul>
<li class="chapter" data-level="" data-path="reading-4.html"><a href="reading-4.html#references"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html"><i class="fa fa-check"></i><b>5.3</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#section-64"><i class="fa fa-check"></i><b>5.3.1</b> </a></li>
<li class="chapter" data-level="5.3.2" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#cfaSyntax"><i class="fa fa-check"></i><b>5.3.2</b> </a></li>
<li class="chapter" data-level="5.3.3" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#estimateCfa3F"><i class="fa fa-check"></i><b>5.3.3</b> </a></li>
<li class="chapter" data-level="5.3.4" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#section-65"><i class="fa fa-check"></i><b>5.3.4</b> </a></li>
<li class="chapter" data-level="5.3.5" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#section-66"><i class="fa fa-check"></i><b>5.3.5</b> </a></li>
<li class="chapter" data-level="5.3.6" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html#estimateCfa1F"><i class="fa fa-check"></i><b>5.3.6</b> </a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html"><i class="fa fa-check"></i><b>5.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#basic-cfa"><i class="fa fa-check"></i><b>5.4.1</b> Basic CFA</a></li>
<li class="chapter" data-level="5.4.2" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#post-hoc-model-modifications"><i class="fa fa-check"></i><b>5.4.2</b> Post-Hoc Model Modifications</a></li>
<li class="chapter" data-level="5.4.3" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html#model-comparisons"><i class="fa fa-check"></i><b>5.4.3</b> Model Comparisons</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="extra-resources.html"><a href="extra-resources.html"><i class="fa fa-check"></i><b>5.5</b> Extra Resources</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="fall-break.html"><a href="fall-break.html"><i class="fa fa-check"></i><b>6</b> Fall Break</a></li>
<li class="chapter" data-level="7" data-path="full-sem.html"><a href="full-sem.html"><i class="fa fa-check"></i><b>7</b> Full SEM</a>
<ul>
<li class="chapter" data-level="7.1" data-path="lecture-5.html"><a href="lecture-5.html"><i class="fa fa-check"></i><b>7.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="lecture-5.html"><a href="lecture-5.html#recording"><i class="fa fa-check"></i><b>7.1.1</b> Recording</a></li>
<li class="chapter" data-level="7.1.2" data-path="lecture-5.html"><a href="lecture-5.html#slides-5"><i class="fa fa-check"></i><b>7.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="reading-5.html"><a href="reading-5.html"><i class="fa fa-check"></i><b>7.2</b> Reading</a>
<ul>
<li class="chapter" data-level="" data-path="reading-5.html"><a href="reading-5.html#reference-4"><i class="fa fa-check"></i>Reference</a></li>
<li class="chapter" data-level="" data-path="reading-5.html"><a href="reading-5.html#questions-4"><i class="fa fa-check"></i>Questions</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="at-home-exercises-5.html"><a href="at-home-exercises-5.html"><i class="fa fa-check"></i><b>7.3</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="at-home-exercises-5.html"><a href="at-home-exercises-5.html#section-76"><i class="fa fa-check"></i><b>7.3.1</b> </a></li>
<li class="chapter" data-level="7.3.2" data-path="at-home-exercises-5.html"><a href="at-home-exercises-5.html#section-77"><i class="fa fa-check"></i><b>7.3.2</b> </a></li>
<li class="chapter" data-level="7.3.3" data-path="at-home-exercises-5.html"><a href="at-home-exercises-5.html#section-78"><i class="fa fa-check"></i><b>7.3.3</b> </a></li>
<li class="chapter" data-level="7.3.4" data-path="at-home-exercises-5.html"><a href="at-home-exercises-5.html#semEstimation"><i class="fa fa-check"></i><b>7.3.4</b> </a></li>
<li class="chapter" data-level="7.3.5" data-path="at-home-exercises-5.html"><a href="at-home-exercises-5.html#section-79"><i class="fa fa-check"></i><b>7.3.5</b> </a></li>
<li class="chapter" data-level="7.3.6" data-path="at-home-exercises-5.html"><a href="at-home-exercises-5.html#section-80"><i class="fa fa-check"></i><b>7.3.6</b> </a></li>
<li class="chapter" data-level="7.3.7" data-path="at-home-exercises-5.html"><a href="at-home-exercises-5.html#section-81"><i class="fa fa-check"></i><b>7.3.7</b> </a></li>
<li class="chapter" data-level="7.3.8" data-path="at-home-exercises-5.html"><a href="at-home-exercises-5.html#section-82"><i class="fa fa-check"></i><b>7.3.8</b> </a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html"><i class="fa fa-check"></i><b>7.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html#section-83"><i class="fa fa-check"></i><b>7.4.1</b> </a></li>
<li class="chapter" data-level="7.4.2" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html#toraCFA"><i class="fa fa-check"></i><b>7.4.2</b> </a></li>
<li class="chapter" data-level="7.4.3" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html#section-84"><i class="fa fa-check"></i><b>7.4.3</b> </a></li>
<li class="chapter" data-level="7.4.4" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html#tora1Estimation"><i class="fa fa-check"></i><b>7.4.4</b> </a></li>
<li class="chapter" data-level="7.4.5" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html#section-85"><i class="fa fa-check"></i><b>7.4.5</b> </a></li>
<li class="chapter" data-level="7.4.6" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html#updatedModel"><i class="fa fa-check"></i><b>7.4.6</b> </a></li>
<li class="chapter" data-level="7.4.7" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html#section-86"><i class="fa fa-check"></i><b>7.4.7</b> </a></li>
<li class="chapter" data-level="7.4.8" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html#section-87"><i class="fa fa-check"></i><b>7.4.8</b> </a></li>
<li class="chapter" data-level="7.4.9" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html#section-88"><i class="fa fa-check"></i><b>7.4.9</b> </a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="multiple-group-models.html"><a href="multiple-group-models.html"><i class="fa fa-check"></i><b>8</b> Multiple Group Models</a>
<ul>
<li class="chapter" data-level="8.1" data-path="lecture-6.html"><a href="lecture-6.html"><i class="fa fa-check"></i><b>8.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="lecture-6.html"><a href="lecture-6.html#recordings-5"><i class="fa fa-check"></i><b>8.1.1</b> Recordings</a></li>
<li class="chapter" data-level="8.1.2" data-path="lecture-6.html"><a href="lecture-6.html#slides-6"><i class="fa fa-check"></i><b>8.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="reading-6.html"><a href="reading-6.html"><i class="fa fa-check"></i><b>8.2</b> Reading</a></li>
<li class="chapter" data-level="8.3" data-path="at-home-exercises-6.html"><a href="at-home-exercises-6.html"><i class="fa fa-check"></i><b>8.3</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="at-home-exercises-6.html"><a href="at-home-exercises-6.html#mgPathAnalysis"><i class="fa fa-check"></i><b>8.3.1</b> Multiple-Group Path Analysis</a></li>
<li class="chapter" data-level="8.3.2" data-path="at-home-exercises-6.html"><a href="at-home-exercises-6.html#mgCFA"><i class="fa fa-check"></i><b>8.3.2</b> Multiple-Group CFA</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="in-class-exercises-6.html"><a href="in-class-exercises-6.html"><i class="fa fa-check"></i><b>8.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="in-class-exercises-6.html"><a href="in-class-exercises-6.html#setup-5"><i class="fa fa-check"></i><b>8.4.1</b> Setup</a></li>
<li class="chapter" data-level="8.4.2" data-path="in-class-exercises-6.html"><a href="in-class-exercises-6.html#w8MeasurementInvariance"><i class="fa fa-check"></i><b>8.4.2</b> Measurement Invariance</a></li>
<li class="chapter" data-level="8.4.3" data-path="in-class-exercises-6.html"><a href="in-class-exercises-6.html#testing-between-group-differences"><i class="fa fa-check"></i><b>8.4.3</b> Testing Between-Group Differences</a></li>
<li class="chapter" data-level="8.4.4" data-path="in-class-exercises-6.html"><a href="in-class-exercises-6.html#multiple-group-sem-for-moderation"><i class="fa fa-check"></i><b>8.4.4</b> Multiple-Group SEM for Moderation</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to Structural Equation Modeling</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="in-class-exercises-1" class="section level2 hasAnchor" number="2.4">
<h2><span class="header-section-number">2.4</span> In-Class Exercises<a href="in-class-exercises-1.html#in-class-exercises-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>During this practical, you will work through some exercises meant to expand your statistical reasoning skills and
improve your understanding of linear models.</p>
<p>For this exercise, having some familiarity with regression will be helpful. If you feel like you need to refresh your
knowledge in this area, consider the resources listed in the <a href="learning-goals.html#background">background knowledge</a> section.</p>
<div id="setup-1" class="section level3 hasAnchor" number="2.4.1">
<h3><span class="header-section-number">2.4.1</span> Setup<a href="in-class-exercises-1.html#setup-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Data:</strong></p>
<p>You will use the following dataset for these exercises.</p>
<ul>
<li><a href="https://surfdrive.surf.nl/files/index.php/s/krD0qT5HFHPqblM">Sesam.sav</a></li>
<li><a href="https://surfdrive.surf.nl/files/index.php/s/XPhLkHtMcbxYB6o">Drivers.sav</a></li>
</ul>
<hr />
<p><strong>Packages:</strong></p>
<p>To complete these exercises, you will need to install the packages described in the following table.</p>
<table>
<colgroup>
<col width="10%" />
<col width="89%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Package</th>
<th align="left">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">lavaan</td>
<td align="left">A sophisticated and user-friendly package for structural equation modeling</td>
</tr>
<tr class="even">
<td align="left">dplyr</td>
<td align="left">A powerful suite of data-processing tools</td>
</tr>
<tr class="odd">
<td align="left">magrittr</td>
<td align="left">Fancy pipe operators</td>
</tr>
<tr class="even">
<td align="left">ggplot2</td>
<td align="left">A flexible and user-friendly package for making graphs</td>
</tr>
<tr class="odd">
<td align="left">psych</td>
<td align="left">Descriptive statistics and tests of bivariate association</td>
</tr>
</tbody>
</table>
<p>Use the <code>install.packages()</code> function to install these packages.</p>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="in-class-exercises-1.html#cb16-1" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="fu">c</span>(<span class="st">&quot;lavaan&quot;</span>, <span class="st">&quot;magrittr&quot;</span>, <span class="st">&quot;ggplot2&quot;</span>, <span class="st">&quot;psych&quot;</span>), <span class="at">dependencies =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
</details>
<hr />
</div>
<div id="data-exploration" class="section level3 hasAnchor" number="2.4.2">
<h3><span class="header-section-number">2.4.2</span> Data Exploration<a href="in-class-exercises-1.html#data-exploration" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<hr />
<p>Load the “Sesam.sav” data.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="in-class-exercises-1.html#cb17-1" tabindex="-1"></a><span class="co"># Load the `dplyr` package for data processing</span></span>
<span id="cb17-2"><a href="in-class-exercises-1.html#cb17-2" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb17-3"><a href="in-class-exercises-1.html#cb17-3" tabindex="-1"></a></span>
<span id="cb17-4"><a href="in-class-exercises-1.html#cb17-4" tabindex="-1"></a><span class="co"># Load the `haven` package for reading in SPSS files:</span></span>
<span id="cb17-5"><a href="in-class-exercises-1.html#cb17-5" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb17-6"><a href="in-class-exercises-1.html#cb17-6" tabindex="-1"></a></span>
<span id="cb17-7"><a href="in-class-exercises-1.html#cb17-7" tabindex="-1"></a><span class="do">## Load the &#39;Sesam.sav&#39; data</span></span>
<span id="cb17-8"><a href="in-class-exercises-1.html#cb17-8" tabindex="-1"></a><span class="do">## Use haven::zap_formats() to remove SPSS attributes</span></span>
<span id="cb17-9"><a href="in-class-exercises-1.html#cb17-9" tabindex="-1"></a>sesam <span class="ot">&lt;-</span> <span class="fu">read_sav</span>(<span class="at">file =</span> <span class="st">&quot;Sesam.sav&quot;</span>) <span class="sc">|&gt;</span> <span class="fu">zap_formats</span>()</span></code></pre></div>
<hr />
<p>This file is part of a larger dataset that evaluates the impact of the first year of the Sesame Street television
series. Sesame Street is mainly concerned with teaching preschool related skills to children in the 3–5 year age range.</p>
<p>The following variables will be used in these exercises:</p>
<ul>
<li><strong>age</strong>: Ages measured in months</li>
<li><strong>prelet</strong>: Knowledge of letters before watching Sesame Street (range: 0–58)</li>
<li><strong>prenumb</strong>: Knowledge of numbers before watching Sesame Street (range: 0–54)</li>
<li><strong>prerelat</strong>: Knowledge of size/amount/position relationships before watching Sesame Street (range: 0–17)</li>
<li><strong>peabody</strong>: Vocabulary maturity before watching Sesame Street (range: 20–120)</li>
<li><strong>postnumb</strong>: Knowledge of numbers after a year of watching Sesame Street (range: 0–54)</li>
</ul>
<p><em>Note</em>: Unless stated otherwise, the following questions refer to the <code>sesam</code> data and the above variables.</p>
<hr />
<div id="section-3" class="section level4" number="2.4.2.1">
<h4><span class="header-section-number">2.4.2.1</span> </h4>
<p>What is the type of each variable?</p>
<p><em>Hint:</em> The output of the <code>str()</code> function should be helpful here.</p>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="in-class-exercises-1.html#cb18-1" tabindex="-1"></a><span class="do">## Examine the data structure:</span></span>
<span id="cb18-2"><a href="in-class-exercises-1.html#cb18-2" tabindex="-1"></a><span class="fu">str</span>(sesam)</span></code></pre></div>
<pre><code>## tibble [240 × 8] (S3: tbl_df/tbl/data.frame)
##  $ id      : num [1:240] 1 2 3 4 5 6 7 8 9 10 ...
##  $ age     : num [1:240] 66 67 56 49 69 54 47 51 69 53 ...
##  $ prelet  : num [1:240] 23 26 14 11 47 26 12 48 44 38 ...
##  $ prenumb : num [1:240] 40 39 9 14 51 33 13 52 42 31 ...
##  $ prerelat: num [1:240] 14 16 9 9 17 14 11 15 15 10 ...
##  $ peabody : num [1:240] 62 80 32 27 71 32 28 38 49 32 ...
##  $ postnumb: num [1:240] 44 39 40 19 54 39 44 51 48 52 ...
##  $ gain    : num [1:240] 4 0 31 5 3 6 31 -1 6 21 ...
##   ..- attr(*, &quot;display_width&quot;)= int 10</code></pre>
<details>
<summary>
Click for explanation
</summary>
<p>All variables are numeric. <code>str()</code> uses the abbreviation “num” to indicate a numeric vector.</p>
</details>
</details>
<hr />
</div>
<div id="section-4" class="section level4" number="2.4.2.2">
<h4><span class="header-section-number">2.4.2.2</span> </h4>
<ul>
<li>What is the average age in the sample?</li>
<li>What is the age range (youngest and oldest child)?</li>
</ul>
<p><em>Hint:</em> Use <code>tidySEM::descriptives()</code></p>
<details>
<summary>
Click to show code
</summary>
<p>As in the take home exercises, you can use the <code>descriptives()</code> function from the <code>tidySEM</code> package to describe the
data:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="in-class-exercises-1.html#cb20-1" tabindex="-1"></a><span class="fu">library</span>(tidySEM)</span>
<span id="cb20-2"><a href="in-class-exercises-1.html#cb20-2" tabindex="-1"></a></span>
<span id="cb20-3"><a href="in-class-exercises-1.html#cb20-3" tabindex="-1"></a><span class="fu">descriptives</span>(sesam)</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["name"],"name":[1],"type":["chr"],"align":["left"]},{"label":["type"],"name":[2],"type":["chr"],"align":["left"]},{"label":["n"],"name":[3],"type":["int"],"align":["right"]},{"label":["missing"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["unique"],"name":[5],"type":["int"],"align":["right"]},{"label":["mean"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["median"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["mode"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["mode_value"],"name":[9],"type":["lgl"],"align":["right"]},{"label":["sd"],"name":[10],"type":["dbl"],"align":["right"]},{"label":["v"],"name":[11],"type":["lgl"],"align":["right"]},{"label":["min"],"name":[12],"type":["dbl"],"align":["right"]},{"label":["max"],"name":[13],"type":["dbl"],"align":["right"]},{"label":["range"],"name":[14],"type":["dbl"],"align":["right"]},{"label":["skew"],"name":[15],"type":["dbl"],"align":["right"]},{"label":["skew_2se"],"name":[16],"type":["dbl"],"align":["right"]},{"label":["kurt"],"name":[17],"type":["dbl"],"align":["right"]},{"label":["kurt_2se"],"name":[18],"type":["dbl"],"align":["right"]}],"data":[{"1":"id","2":"numeric","3":"240","4":"0","5":"240","6":"120.500000","7":"120.5","8":"120.5","9":"NA","10":"69.426220","11":"NA","12":"1","13":"240","14":"239","15":"0.000000000","16":"0.000000000","17":"-1.2000000","18":"-1.9168624"},{"1":"age","2":"numeric","3":"240","4":"0","5":"33","6":"51.525000","7":"52.0","8":"52.0","9":"NA","10":"6.281356","11":"NA","12":"34","13":"69","14":"35","15":"-0.236483867","16":"-0.752473939","17":"0.3716628","18":"0.5936886"},{"1":"prelet","2":"numeric","3":"240","4":"0","5":"40","6":"15.937500","7":"14.0","8":"14.0","9":"NA","10":"8.536425","11":"NA","12":"1","13":"55","14":"54","15":"1.994292900","16":"6.345690518","17":"4.9597668","18":"7.9226588"},{"1":"prenumb","2":"numeric","3":"240","4":"0","5":"47","6":"20.895833","7":"19.0","8":"19.0","9":"NA","10":"10.685382","11":"NA","12":"1","13":"52","14":"51","15":"0.738826532","16":"2.350890644","17":"0.1319418","18":"0.2107619"},{"1":"prerelat","2":"numeric","3":"240","4":"0","5":"16","6":"9.937500","7":"10.0","8":"10.0","9":"NA","10":"3.073753","11":"NA","12":"2","13":"17","14":"15","15":"-0.179511084","16":"-0.571190814","17":"-0.4378466","18":"-0.6994097"},{"1":"peabody","2":"numeric","3":"240","4":"0","5":"46","6":"46.775000","7":"42.0","8":"42.0","9":"NA","10":"15.986900","11":"NA","12":"27","13":"99","14":"72","15":"1.039843714","16":"3.308704752","17":"0.5306226","18":"0.8476088"},{"1":"postnumb","2":"numeric","3":"240","4":"0","5":"50","6":"30.054167","7":"29.0","8":"29.0","9":"NA","10":"12.845769","11":"NA","12":"0","13":"54","14":"54","15":"0.002795098","16":"0.008893791","17":"-1.0836441","18":"-1.7309972"},{"1":"gain","2":"numeric","3":"240","4":"0","5":"45","6":"9.158333","7":"9.0","8":"9.0","9":"NA","10":"9.682401","11":"NA","12":"-35","13":"33","14":"68","15":"-0.398863307","16":"-1.269153143","17":"1.9834557","18":"3.1683430"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<details>
<summary>
Click for explanation
</summary>
<p>We can get the average age from the “mean” column in the table (51.5), and the age range
from the columns “min” and “max”, (34 and 69, respectively.)</p>
</details>
</details>
<hr />
</div>
<div id="changeScore" class="section level4" number="2.4.2.3">
<h4><span class="header-section-number">2.4.2.3</span> </h4>
<ul>
<li>What is the average gain in knowledge of numbers?</li>
<li>What is the standard deviation of this gain?</li>
</ul>
<p><em>Hints:</em></p>
<ul>
<li>You will need to compute the gain and save the change score as a new object.</li>
<li>You can then use the base-R functions <code>mean()</code> and <code>sd()</code> to do the calculations.</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<p>Create a new variable that represents the difference between pre- and post-test scores on knowledge of numbers:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="in-class-exercises-1.html#cb21-1" tabindex="-1"></a>sesam <span class="ot">&lt;-</span> <span class="fu">mutate</span>(sesam, <span class="at">ndif =</span> postnumb <span class="sc">-</span> prenumb)</span></code></pre></div>
<p>Compute the mean and SD of the change score:</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="in-class-exercises-1.html#cb22-1" tabindex="-1"></a>sesam <span class="sc">|&gt;</span> <span class="fu">summarise</span>(<span class="fu">mean</span>(ndif), <span class="fu">sd</span>(ndif))</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["mean(ndif)"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["sd(ndif)"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"9.158333","2":"9.682401"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</details>
<hr />
</div>
<div id="section-5" class="section level4" number="2.4.2.4">
<h4><span class="header-section-number">2.4.2.4</span> </h4>
<ul>
<li>Create an appropriate visualization of the gain scores you computed in <a href="in-class-exercises-1.html#changeScore">2.4.2.3</a>.</li>
<li>Justify your choice of visualization.</li>
</ul>
<p><em>Hint:</em> Recall the visualizations for continuous variables covered in the
<a href="in-class-exercises.html">Week 1 In-Class Exercises</a></p>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="in-class-exercises-1.html#cb23-1" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb23-2"><a href="in-class-exercises-1.html#cb23-2" tabindex="-1"></a></span>
<span id="cb23-3"><a href="in-class-exercises-1.html#cb23-3" tabindex="-1"></a><span class="do">## Create an empty baseline plot object:</span></span>
<span id="cb23-4"><a href="in-class-exercises-1.html#cb23-4" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(sesam, <span class="fu">aes</span>(<span class="at">x =</span> ndif))</span>
<span id="cb23-5"><a href="in-class-exercises-1.html#cb23-5" tabindex="-1"></a></span>
<span id="cb23-6"><a href="in-class-exercises-1.html#cb23-6" tabindex="-1"></a><span class="do">## Add some appropriate geoms:</span></span>
<span id="cb23-7"><a href="in-class-exercises-1.html#cb23-7" tabindex="-1"></a>p <span class="sc">+</span> <span class="fu">geom_histogram</span>()</span></code></pre></div>
<p><img src="isem_files/figure-html/unnamed-chunk-85-1.png" alt="" width="672" /></p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="in-class-exercises-1.html#cb24-1" tabindex="-1"></a>p <span class="sc">+</span> <span class="fu">geom_density</span>()</span></code></pre></div>
<p><img src="isem_files/figure-html/unnamed-chunk-85-2.png" alt="" width="672" /></p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="in-class-exercises-1.html#cb25-1" tabindex="-1"></a>p <span class="sc">+</span> <span class="fu">geom_boxplot</span>()</span></code></pre></div>
<p><img src="isem_files/figure-html/unnamed-chunk-85-3.png" alt="" width="672" /></p>
<details>
<summary>
Click for explanation
</summary>
<p>Because the gain score is numeric, we should use something appropriate for showing the distribution of a continuous
variable. In this case, we can use either a density plot, or a histogram (remember from the lecture, this is like a
density plot, but binned).</p>
<p>We can also use a box plot, which can be a concise way to display a lot of information about a variable in a little
less space.</p>
</details>
</details>
<hr />
</div>
<div id="section-6" class="section level4" number="2.4.2.5">
<h4><span class="header-section-number">2.4.2.5</span> </h4>
<ul>
<li>Create a visualization that provides information about the bivariate relationship between the pre- and post-test
number knowledge.</li>
<li>Justify your choice of visualization. Describe the relationship based on what you see in your visualization.</li>
</ul>
<p><em>Hint:</em> Again, some of the visualizations covered in the <a href="in-class-exercises.html">Week 1 In-Class Exercises</a> may be
useful.</p>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="in-class-exercises-1.html#cb26-1" tabindex="-1"></a><span class="do">## Create a scatterplot of the pre- and post-test number knowledge</span></span>
<span id="cb26-2"><a href="in-class-exercises-1.html#cb26-2" tabindex="-1"></a><span class="fu">ggplot</span>(sesam, <span class="fu">aes</span>(<span class="at">x =</span> prenumb, <span class="at">y =</span> postnumb)) <span class="sc">+</span></span>
<span id="cb26-3"><a href="in-class-exercises-1.html#cb26-3" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code></pre></div>
<p><img src="isem_files/figure-html/unnamed-chunk-86-1.png" alt="" width="672" /></p>
<details>
<summary>
Click for explanation
</summary>
<p>A scatterplot is a good tool for showing patterns in the way that two continuous variables relate to each other. From
it, we can quickly gather information about whether a relationship exists, its direction, its strength, how much
variation there is, and whether or not a relationship might be non-linear.</p>
<p>Based on this scatterplot, we see a positive relationship between the prior knowledge of numbers and the knowledge of
numbers at the end of the study. Children who started with a higher level of numeracy also ended with a higher level
of numeracy.</p>
<p>There is a considerable amount of variance in the relationship. Not every child increases their numeracy between
pre-test and post-test. Children show differing amounts of increase.</p>
</details>
</details>
<hr />
</div>
</div>
<div id="linear-modeling" class="section level3 hasAnchor" number="2.4.3">
<h3><span class="header-section-number">2.4.3</span> Linear Modeling<a href="in-class-exercises-1.html#linear-modeling" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<hr />
<div id="section-7" class="section level4" number="2.4.3.1">
<h4><span class="header-section-number">2.4.3.1</span> </h4>
<p>Are there significant, bivariate associations between <em>postnumb</em> and the following variables?</p>
<ul>
<li><em>age</em></li>
<li><em>prelet</em></li>
<li><em>prenumb</em></li>
<li><em>prerelat</em></li>
<li><em>peabody</em></li>
</ul>
<p>Use Pearson correlations to answer this question.</p>
<ul>
<li>You do not need to check the assumptions here (though you would in real life).</li>
</ul>
<p><em>Hint:</em> The base-R <code>cor.test()</code> function and the <code>corr.test()</code> function from the <code>psych</code> package will both conduct
hypothesis tests for a correlation coefficients (the base-R <code>cor()</code> function only computes the coefficients).</p>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="in-class-exercises-1.html#cb27-1" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb27-2"><a href="in-class-exercises-1.html#cb27-2" tabindex="-1"></a></span>
<span id="cb27-3"><a href="in-class-exercises-1.html#cb27-3" tabindex="-1"></a><span class="do">## Test the correlations using psych::corr.test():</span></span>
<span id="cb27-4"><a href="in-class-exercises-1.html#cb27-4" tabindex="-1"></a>sesam <span class="sc">|&gt;</span></span>
<span id="cb27-5"><a href="in-class-exercises-1.html#cb27-5" tabindex="-1"></a>  <span class="fu">select</span>(postnumb, age, prelet, prenumb, prerelat, peabody) <span class="sc">|&gt;</span></span>
<span id="cb27-6"><a href="in-class-exercises-1.html#cb27-6" tabindex="-1"></a>  <span class="fu">corr.test</span>()</span></code></pre></div>
<pre><code>## Call:corr.test(x = select(sesam, postnumb, age, prelet, prenumb, prerelat, 
##     peabody))
## Correlation matrix 
##          postnumb  age prelet prenumb prerelat peabody
## postnumb     1.00 0.34   0.50    0.68     0.54    0.52
## age          0.34 1.00   0.33    0.43     0.44    0.29
## prelet       0.50 0.33   1.00    0.72     0.47    0.40
## prenumb      0.68 0.43   0.72    1.00     0.72    0.61
## prerelat     0.54 0.44   0.47    0.72     1.00    0.56
## peabody      0.52 0.29   0.40    0.61     0.56    1.00
## Sample Size 
## [1] 240
## Probability values (Entries above the diagonal are adjusted for multiple tests.) 
##          postnumb age prelet prenumb prerelat peabody
## postnumb        0   0      0       0        0       0
## age             0   0      0       0        0       0
## prelet          0   0      0       0        0       0
## prenumb         0   0      0       0        0       0
## prerelat        0   0      0       0        0       0
## peabody         0   0      0       0        0       0
## 
##  To see confidence intervals of the correlations, print with the short=FALSE option</code></pre>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="in-class-exercises-1.html#cb29-1" tabindex="-1"></a><span class="do">## OR ##</span></span>
<span id="cb29-2"><a href="in-class-exercises-1.html#cb29-2" tabindex="-1"></a></span>
<span id="cb29-3"><a href="in-class-exercises-1.html#cb29-3" tabindex="-1"></a><span class="fu">library</span>(magrittr)</span>
<span id="cb29-4"><a href="in-class-exercises-1.html#cb29-4" tabindex="-1"></a></span>
<span id="cb29-5"><a href="in-class-exercises-1.html#cb29-5" tabindex="-1"></a><span class="do">## Test the correlations using multiple cor.test() calls:</span></span>
<span id="cb29-6"><a href="in-class-exercises-1.html#cb29-6" tabindex="-1"></a>sesam <span class="sc">%$%</span> <span class="fu">cor.test</span>(postnumb, age)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  postnumb and age
## t = 5.5972, df = 238, p-value = 5.979e-08
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.2241066 0.4483253
## sample estimates:
##       cor 
## 0.3410578</code></pre>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="in-class-exercises-1.html#cb31-1" tabindex="-1"></a>sesam <span class="sc">%$%</span> <span class="fu">cor.test</span>(postnumb, prelet)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  postnumb and prelet
## t = 8.9986, df = 238, p-value &lt; 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.4029239 0.5926632
## sample estimates:
##       cor 
## 0.5038464</code></pre>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="in-class-exercises-1.html#cb33-1" tabindex="-1"></a>sesam <span class="sc">%$%</span> <span class="fu">cor.test</span>(postnumb, prenumb)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  postnumb and prenumb
## t = 14.133, df = 238, p-value &lt; 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.6002172 0.7389277
## sample estimates:
##       cor 
## 0.6755051</code></pre>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="in-class-exercises-1.html#cb35-1" tabindex="-1"></a>sesam <span class="sc">%$%</span> <span class="fu">cor.test</span>(postnumb, prerelat)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  postnumb and prerelat
## t = 9.9857, df = 238, p-value &lt; 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.4475469 0.6268773
## sample estimates:
##       cor 
## 0.5433818</code></pre>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="in-class-exercises-1.html#cb37-1" tabindex="-1"></a>sesam <span class="sc">%$%</span> <span class="fu">cor.test</span>(postnumb, peabody)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  postnumb and peabody
## t = 9.395, df = 238, p-value &lt; 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.4212427 0.6067923
## sample estimates:
##      cor 
## 0.520128</code></pre>
<details>
<summary>
Click for explanation
</summary>
<p>Yes, based on the p-values (remember that 0 here really means very small, making it less than .05), we would say that
there are significant correlations between postnumb and all other variables in the data. (In fact, all variables in
the data are significantly correlated with one another.)</p>
</details>
</details>
<hr />
</div>
<div id="reg1" class="section level4" number="2.4.3.2">
<h4><span class="header-section-number">2.4.3.2</span> </h4>
<p>Do <em>age</em> and <em>prenumb</em> explain a significant proportion of the variance in
<em>postnumb</em>?</p>
<ul>
<li>What statistic did you use to justify your conclusion?</li>
<li>Interpret the model fit.</li>
<li>Use the <code>lm()</code> function to fit your model.</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="in-class-exercises-1.html#cb39-1" tabindex="-1"></a>lmOut <span class="ot">&lt;-</span> <span class="fu">lm</span>(postnumb <span class="sc">~</span> age <span class="sc">+</span> prenumb, <span class="at">data =</span> sesam)</span>
<span id="cb39-2"><a href="in-class-exercises-1.html#cb39-2" tabindex="-1"></a><span class="fu">summary</span>(lmOut)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = postnumb ~ age + prenumb, data = sesam)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -38.130  -6.456  -0.456   5.435  22.568 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   7.4242     5.1854   1.432    0.154    
## age           0.1225     0.1084   1.131    0.259    
## prenumb       0.7809     0.0637  12.259   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 9.486 on 237 degrees of freedom
## Multiple R-squared:  0.4592, Adjusted R-squared:  0.4547 
## F-statistic: 100.6 on 2 and 237 DF,  p-value: &lt; 2.2e-16</code></pre>
<details>
<summary>
Click for explanation
</summary>
<ul>
<li>Yes, <em>age</em> and <em>prenumb</em> explain a significant amount of variability in <em>postnumb</em>
<span class="math inline">\((R^2 = 0.459,\)</span>
<span class="math inline">\(F[2, 237] = 100.629,\)</span>
<span class="math inline">\(p &lt; 0.001).\)</span>
<ul>
<li>We use the F statistic for the overall test of model fit to support this conclusion.</li>
<li>The variables <em>age</em> and <em>prenumb</em> together explain 45.9% of the variability in <em>postnumb</em>.</li>
</ul>
</details></li>
</ul>
</details>
<hr />
</div>
<div id="section-8" class="section level4" number="2.4.3.3">
<h4><span class="header-section-number">2.4.3.3</span> </h4>
<p>Write the null and alternative hypotheses tested for in <a href="in-class-exercises-1.html#reg1">2.4.3.2</a>.</p>
<details>
<summary>
Click for explanation
</summary>
<p>Since we are testing for explained variance, our hypotheses concern the <span class="math inline">\(R^2\)</span>.</p>
<p><span class="math display">\[
\begin{align*}
H_0: R^2 = 0\\
H_1: R^2 &gt; 0
\end{align*}
\]</span></p>
<p>Note that this is a directional hypotheses because the <span class="math inline">\(R^2\)</span> cannot be negative.</p>
</details>
<hr />
</div>
<div id="syntax1" class="section level4" number="2.4.3.4">
<h4><span class="header-section-number">2.4.3.4</span> </h4>
<p>Define the model syntax to estimate the model from <a href="in-class-exercises-1.html#reg1">2.4.3.2</a> as a path analysis using <code>lavaan</code>.</p>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="in-class-exercises-1.html#cb41-1" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="st">&#39;postnumb ~ 1 + age + prenumb&#39;</span></span></code></pre></div>
</details>
<hr />
</div>
<div id="path1" class="section level4" number="2.4.3.5">
<h4><span class="header-section-number">2.4.3.5</span> </h4>
<p>Estimate the path analytic model you defined above.</p>
<ul>
<li>Use the <code>lavaan::sem()</code> function to estimate the model.</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="in-class-exercises-1.html#cb42-1" tabindex="-1"></a><span class="fu">library</span>(lavaan)</span>
<span id="cb42-2"><a href="in-class-exercises-1.html#cb42-2" tabindex="-1"></a></span>
<span id="cb42-3"><a href="in-class-exercises-1.html#cb42-3" tabindex="-1"></a>lavOut1 <span class="ot">&lt;-</span> <span class="fu">sem</span>(mod, <span class="at">data =</span> sesam)</span></code></pre></div>
</details>
<hr />
</div>
<div id="section-9" class="section level4" number="2.4.3.6">
<h4><span class="header-section-number">2.4.3.6</span> </h4>
<p>Summarize the fitted model you estimated above.</p>
<ul>
<li>Use the <code>summary()</code> function to summarize the model.</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="in-class-exercises-1.html#cb43-1" tabindex="-1"></a><span class="fu">summary</span>(lavOut1)</span></code></pre></div>
<pre><code>## lavaan 0.7-2 ended normally after 1 iteration
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                         4
## 
##   Number of observations                           240
## 
## Model Test User Model:
##                                                       
##   Test statistic                                 0.000
##   Degrees of freedom                                 0
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   postnumb ~                                          
##     age               0.123    0.108    1.138    0.255
##     prenumb           0.781    0.063   12.336    0.000
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .postnumb          7.424    5.153    1.441    0.150
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .postnumb         88.864    8.112   10.954    0.000</code></pre>
</details>
<hr />
<p>In OLS regression, the predictor variables are usually treated as fixed and do not covary. We can easily relax this
assumption in path analysis.</p>
<hr />
</div>
<div id="section-10" class="section level4" number="2.4.3.7">
<h4><span class="header-section-number">2.4.3.7</span> </h4>
<p>Re-estimate the path analytic model you defined in <a href="in-class-exercises-1.html#syntax1">2.4.3.4</a>.</p>
<ul>
<li>Specify the predictors as random, correlated variables.</li>
</ul>
<p><em>Hint:</em> You can make the predictors random in, at least, two ways:</p>
<ol style="list-style-type: decimal">
<li>Modify the model syntax to specify the correlation between <code>age</code> and
<code>prenumb</code>.</li>
<li>Add <code>fixed.x = FALSE</code> to your <code>sem()</code> call.</li>
</ol>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="in-class-exercises-1.html#cb45-1" tabindex="-1"></a>lavOut2 <span class="ot">&lt;-</span> <span class="fu">sem</span>(mod, <span class="at">data =</span> sesam, <span class="at">fixed.x =</span> <span class="cn">FALSE</span>)</span>
<span id="cb45-2"><a href="in-class-exercises-1.html#cb45-2" tabindex="-1"></a></span>
<span id="cb45-3"><a href="in-class-exercises-1.html#cb45-3" tabindex="-1"></a><span class="do">## OR ##</span></span>
<span id="cb45-4"><a href="in-class-exercises-1.html#cb45-4" tabindex="-1"></a></span>
<span id="cb45-5"><a href="in-class-exercises-1.html#cb45-5" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="st">&#39;</span></span>
<span id="cb45-6"><a href="in-class-exercises-1.html#cb45-6" tabindex="-1"></a><span class="st">postnumb ~ 1 + age + prenumb</span></span>
<span id="cb45-7"><a href="in-class-exercises-1.html#cb45-7" tabindex="-1"></a><span class="st">age ~~ prenumb</span></span>
<span id="cb45-8"><a href="in-class-exercises-1.html#cb45-8" tabindex="-1"></a><span class="st">&#39;</span></span>
<span id="cb45-9"><a href="in-class-exercises-1.html#cb45-9" tabindex="-1"></a></span>
<span id="cb45-10"><a href="in-class-exercises-1.html#cb45-10" tabindex="-1"></a>lavOut2 <span class="ot">&lt;-</span> <span class="fu">sem</span>(mod, <span class="at">data =</span> sesam)</span></code></pre></div>
</details>
<hr />
</div>
<div id="section-11" class="section level4" number="2.4.3.8">
<h4><span class="header-section-number">2.4.3.8</span> </h4>
<p>Summarize the fitted model you estimated above.</p>
<ul>
<li>Compare the results to those from the OLS regression in <a href="in-class-exercises-1.html#reg1">2.4.3.2</a> and the path model in <a href="in-class-exercises-1.html#path1">2.4.3.5</a>.</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="in-class-exercises-1.html#cb46-1" tabindex="-1"></a><span class="fu">summary</span>(lavOut2)</span></code></pre></div>
<pre><code>## lavaan 0.7-2 ended normally after 27 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                         9
## 
##   Number of observations                           240
## 
## Model Test User Model:
##                                                       
##   Test statistic                                 0.000
##   Degrees of freedom                                 0
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   postnumb ~                                          
##     age               0.123    0.108    1.138    0.255
##     prenumb           0.781    0.063   12.336    0.000
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   age ~~                                              
##     prenumb          28.930    4.701    6.154    0.000
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .postnumb          7.424    5.153    1.441    0.150
##     age              51.525    0.405  127.344    0.000
##     prenumb          20.896    0.688   30.359    0.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .postnumb         88.864    8.112   10.954    0.000
##     age              39.291    3.587   10.954    0.000
##     prenumb         113.702   10.379   10.954    0.000</code></pre>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="in-class-exercises-1.html#cb48-1" tabindex="-1"></a><span class="fu">summary</span>(lavOut1)</span></code></pre></div>
<pre><code>## lavaan 0.7-2 ended normally after 1 iteration
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                         4
## 
##   Number of observations                           240
## 
## Model Test User Model:
##                                                       
##   Test statistic                                 0.000
##   Degrees of freedom                                 0
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   postnumb ~                                          
##     age               0.123    0.108    1.138    0.255
##     prenumb           0.781    0.063   12.336    0.000
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .postnumb          7.424    5.153    1.441    0.150
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .postnumb         88.864    8.112   10.954    0.000</code></pre>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="in-class-exercises-1.html#cb50-1" tabindex="-1"></a><span class="fu">summary</span>(lmOut)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = postnumb ~ age + prenumb, data = sesam)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -38.130  -6.456  -0.456   5.435  22.568 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   7.4242     5.1854   1.432    0.154    
## age           0.1225     0.1084   1.131    0.259    
## prenumb       0.7809     0.0637  12.259   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 9.486 on 237 degrees of freedom
## Multiple R-squared:  0.4592, Adjusted R-squared:  0.4547 
## F-statistic: 100.6 on 2 and 237 DF,  p-value: &lt; 2.2e-16</code></pre>
</details>
<hr />
</div>
<div id="section-12" class="section level4" number="2.4.3.9">
<h4><span class="header-section-number">2.4.3.9</span> </h4>
<p>Consider the path model below.</p>
<ul>
<li>How many regression coefficients are estimated in this model?</li>
<li>How many variances are estimated?</li>
<li>How many covariances are estimated?</li>
</ul>
<p><img src="isem_files/figure-html/unnamed-chunk-95-1.png" alt="" width="672" /></p>
<details>
<summary>
Click for explanation
</summary>
<ul>
<li>Six regression coefficients (red)</li>
<li>Four (residual) variances (blue)</li>
<li>No covariances</li>
</ul>
<p><img src="isem_files/figure-html/unnamed-chunk-96-1.png" alt="" width="672" /></p>
</details>
<hr />
</div>
<div id="section-13" class="section level4" number="2.4.3.10">
<h4><span class="header-section-number">2.4.3.10</span> </h4>
<p>Consider a multiple regression analysis with three continuous independent variables: scores on tests of language,
history, and logic, and one continuous dependent variable: score on a math test. We want to know if scores on the
language, history, and logic tests can predict the math test score.</p>
<ul>
<li>Sketch a path model that you could use to answer this question</li>
<li>How many regression parameters are there?</li>
<li>How many variances could you estimate?</li>
<li>How many covariances could you estimate?</li>
</ul>
<hr />
</div>
</div>
<div id="categorical-ivs" class="section level3 hasAnchor" number="2.4.4">
<h3><span class="header-section-number">2.4.4</span> Categorical IVs<a href="in-class-exercises-1.html#categorical-ivs" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<hr />
<p>Load the <code>Drivers.sav</code> data.</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="in-class-exercises-1.html#cb52-1" tabindex="-1"></a><span class="co"># Read the data into a data frame named &#39;drivers&#39;:</span></span>
<span id="cb52-2"><a href="in-class-exercises-1.html#cb52-2" tabindex="-1"></a>drivers <span class="ot">&lt;-</span> <span class="fu">read_sav</span>(<span class="st">&quot;Drivers.sav&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb52-3"><a href="in-class-exercises-1.html#cb52-3" tabindex="-1"></a>  <span class="fu">as_factor</span>() <span class="co"># This preserves the SPSS labels for nominal variables</span></span></code></pre></div>
<hr />
<p>In this section, we will evaluate the following research question:</p>
<blockquote>
<p>Does talking on the phone interfere with people’s driving skills?</p>
</blockquote>
<p>These data come from an experiment. The <em>condition</em> variable represents the three experimental conditions:</p>
<ul>
<li>Hand-held phone</li>
<li>Hands-free phone</li>
<li>Control (no phone)</li>
</ul>
<p>We will use <em>condition</em> as the IV in our models. The DV, <em>RT</em>, represents the participant’s reaction time (in
milliseconds) during a driving simulation.</p>
<hr />
<div id="section-14" class="section level4" number="2.4.4.1">
<h4><span class="header-section-number">2.4.4.1</span> </h4>
<p>Use the package <code>ggplot2</code> to create a density plot for the variable <em>RT</em>.</p>
<ul>
<li>What concept are we representing with this plot?</li>
</ul>
<p><em>Hint:</em> Consider the lap times example from
<a href="lecture-1.html#statistical-modeling">the statistical modeling section</a> of Lecture 2.</p>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="in-class-exercises-1.html#cb53-1" tabindex="-1"></a><span class="fu">ggplot</span>(drivers, <span class="fu">aes</span>(<span class="at">x =</span> RT)) <span class="sc">+</span></span>
<span id="cb53-2"><a href="in-class-exercises-1.html#cb53-2" tabindex="-1"></a>  <span class="fu">geom_density</span>()</span></code></pre></div>
<p><img src="isem_files/figure-html/unnamed-chunk-99-1.png" alt="" width="672" /></p>
<details>
<summary>
Click for explanation
</summary>
<p>This shows the distribution of all the combined reaction times from drivers in all three categories.</p>
</details>
</details>
<hr />
</div>
<div id="section-15" class="section level4" number="2.4.4.2">
<h4><span class="header-section-number">2.4.4.2</span> </h4>
<p>Modify this density plot by mapping the variable <em>condition</em> from your data to the <code>fill</code> aesthetic in <code>ggplot</code>.</p>
<ul>
<li>What is the difference between this plot and the previous plot?</li>
<li>Do you think there is evidence for differences between the groups?</li>
<li>How might we test this by fitting a model to our sample?</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<p><em>Hint</em>: To modify the transparency of the densities, use the aesthetic <code>alpha</code>.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="in-class-exercises-1.html#cb54-1" tabindex="-1"></a><span class="fu">ggplot</span>(drivers, <span class="fu">aes</span>(<span class="at">x =</span> RT, <span class="at">fill =</span> condition)) <span class="sc">+</span></span>
<span id="cb54-2"><a href="in-class-exercises-1.html#cb54-2" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> .<span class="dv">5</span>)</span></code></pre></div>
<p><img src="isem_files/figure-html/unnamed-chunk-100-1.png" alt="" width="672" /></p>
<details>
<summary>
Click for explanation
</summary>
<p>This figure models the conditional distribution of reaction time, where the type of cell phone usage is the grouping
factor.</p>
<p>Things you can look at to visually assess whether the three groups differ are the amount of overlap of the
distributions, how much distance there is between the individual means, and whether the combined distribution is much
different than the conditional distributions.</p>
<p>If we are willing to assume that these conditional distributions are normally distributed and have equivalent
variances, we could use a linear model with dummy-coded predictors.</p>
</details>
</details>
<hr />
</div>
<div id="aside-anova-vs.-linear-regression" class="section level4 unnumbered hasAnchor">
<h4>Aside: ANOVA vs. Linear Regression<a href="in-class-exercises-1.html#aside-anova-vs.-linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>As you may know, the mathematical model underlying ANOVA is just a linear regression model with nominal IVs. So, in
terms of the underlying statistical models, there is no difference between ANOVA and regression; the differences lie in
the focus of the analysis.</p>
<ul>
<li>ANOVA is really a type of statistical test wherein we are testing hypotheses about the effects of some set of nominal
grouping factors on some continuous outcome.
<ul>
<li>When doing an ANOVA, we usually don’t interact directly with the parameter estimates from the underlying model.</li>
</ul></li>
<li>Regression is a type of statistical model (i.e., a way to represent a univariate distribution with a conditional mean
and fixed variance).
<ul>
<li>When we do a regression analysis, we primarily focus on the estimated parameters of the underling linear model.</li>
</ul></li>
</ul>
<p>When doing ANOVA in R, we estimate the model exactly as we would for linear regression; we simply summarize the results
differently.</p>
<ul>
<li>If you want to summarize your model in terms of the <em>sums of squares</em> table you usually see when running an ANOVA, you
can supply your fitted <code>lm</code> object to the <code>anova()</code> function.</li>
</ul>
<p>This is a statistical modeling course, not a statistical testing course, so we will not consider ANOVA any further.</p>
<hr />
</div>
<div id="reg2" class="section level4" number="2.4.4.3">
<h4><span class="header-section-number">2.4.4.3</span> </h4>
<p>Estimate a linear model that will answer the research question stated in the beginning of this section.</p>
<ul>
<li>Use <code>lm()</code> to estimate the model.</li>
<li>Summarize the fitted model and use the results to answer the research question.</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="in-class-exercises-1.html#cb55-1" tabindex="-1"></a><span class="fu">library</span>(magrittr)</span>
<span id="cb55-2"><a href="in-class-exercises-1.html#cb55-2" tabindex="-1"></a></span>
<span id="cb55-3"><a href="in-class-exercises-1.html#cb55-3" tabindex="-1"></a>lmOut <span class="ot">&lt;-</span> drivers <span class="sc">|&gt;</span></span>
<span id="cb55-4"><a href="in-class-exercises-1.html#cb55-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">condition =</span> <span class="fu">relevel</span>(condition, <span class="at">ref =</span> <span class="st">&quot;control&quot;</span>)) <span class="sc">%$%</span></span>
<span id="cb55-5"><a href="in-class-exercises-1.html#cb55-5" tabindex="-1"></a>  <span class="fu">lm</span>(RT <span class="sc">~</span> condition)</span>
<span id="cb55-6"><a href="in-class-exercises-1.html#cb55-6" tabindex="-1"></a></span>
<span id="cb55-7"><a href="in-class-exercises-1.html#cb55-7" tabindex="-1"></a><span class="fu">summary</span>(lmOut)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = RT ~ condition)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -317.50  -71.25    2.98   89.55  243.45 
## 
## Coefficients:
##                     Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)           553.75      29.08  19.042   &lt;2e-16 ***
## conditionhand-held    100.75      41.13   2.450   0.0174 *  
## conditionhands-free    63.80      41.13   1.551   0.1264    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 130.1 on 57 degrees of freedom
## Multiple R-squared:  0.09729,    Adjusted R-squared:  0.06562 
## F-statistic: 3.072 on 2 and 57 DF,  p-value: 0.05408</code></pre>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="in-class-exercises-1.html#cb57-1" tabindex="-1"></a><span class="fu">anova</span>(lmOut)</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Df"],"name":[1],"type":["int"],"align":["right"]},{"label":["Sum Sq"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Mean Sq"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["F value"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["Pr(>F)"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"2","2":"103908.7","3":"51954.35","4":"3.071729","5":"0.05408477","_rn_":"condition"},{"1":"57","2":"964081.7","3":"16913.71","4":"NA","5":"NA","_rn_":"Residuals"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<details>
<summary>
Click for explanation
</summary>
<p>The effect of <em>condition</em> on <em>RT</em> is nonsignificant <span class="math inline">\((F[2, 57] = 3.07,\)</span> <span class="math inline">\(p = 0.054).\)</span> Therefore, based on
these results, we do not have evidence for an effect of mobile phone usage on driving performance.</p>
</details>
</details>
<hr />
</div>
<div id="section-16" class="section level4" number="2.4.4.4">
<h4><span class="header-section-number">2.4.4.4</span> </h4>
<p>Use <strong>lavaan</strong> to estimate the model from <a href="in-class-exercises-1.html#reg2">2.4.4.3</a> as a path model.</p>
<p><em>Hint</em>: <strong>lavaan</strong> won’t let us use factors for our categorical predictors. So, you will need to create your own dummy
codes.</p>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="in-class-exercises-1.html#cb58-1" tabindex="-1"></a><span class="do">## Specify the model syntax:</span></span>
<span id="cb58-2"><a href="in-class-exercises-1.html#cb58-2" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="st">&#39;RT ~ 1 + HH + HF&#39;</span></span>
<span id="cb58-3"><a href="in-class-exercises-1.html#cb58-3" tabindex="-1"></a></span>
<span id="cb58-4"><a href="in-class-exercises-1.html#cb58-4" tabindex="-1"></a><span class="do">## Dummy code the factor variable:</span></span>
<span id="cb58-5"><a href="in-class-exercises-1.html#cb58-5" tabindex="-1"></a>drivers2 <span class="ot">&lt;-</span> <span class="fu">mutate</span>(drivers,</span>
<span id="cb58-6"><a href="in-class-exercises-1.html#cb58-6" tabindex="-1"></a>                   <span class="do">## Create dummy code for &quot;hand-held&quot; condition:</span></span>
<span id="cb58-7"><a href="in-class-exercises-1.html#cb58-7" tabindex="-1"></a>                   <span class="at">HH =</span> <span class="fu">ifelse</span>(condition <span class="sc">==</span> <span class="st">&quot;hand-held&quot;</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb58-8"><a href="in-class-exercises-1.html#cb58-8" tabindex="-1"></a>                   <span class="do">## Create dummy code for &quot;hands-free&quot; condition:</span></span>
<span id="cb58-9"><a href="in-class-exercises-1.html#cb58-9" tabindex="-1"></a>                   <span class="at">HF =</span> <span class="fu">ifelse</span>(condition <span class="sc">==</span> <span class="st">&quot;hands-free&quot;</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb58-10"><a href="in-class-exercises-1.html#cb58-10" tabindex="-1"></a>                   )</span>
<span id="cb58-11"><a href="in-class-exercises-1.html#cb58-11" tabindex="-1"></a></span>
<span id="cb58-12"><a href="in-class-exercises-1.html#cb58-12" tabindex="-1"></a><span class="do">## Estimate the path model:</span></span>
<span id="cb58-13"><a href="in-class-exercises-1.html#cb58-13" tabindex="-1"></a>lavOut <span class="ot">&lt;-</span> <span class="fu">sem</span>(mod, <span class="at">data =</span> drivers2)</span>
<span id="cb58-14"><a href="in-class-exercises-1.html#cb58-14" tabindex="-1"></a></span>
<span id="cb58-15"><a href="in-class-exercises-1.html#cb58-15" tabindex="-1"></a><span class="do">## Summarize the results:</span></span>
<span id="cb58-16"><a href="in-class-exercises-1.html#cb58-16" tabindex="-1"></a><span class="fu">summary</span>(lavOut)</span></code></pre></div>
<pre><code>## lavaan 0.7-2 ended normally after 1 iteration
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                         4
## 
##   Number of observations                            60
## 
## Model Test User Model:
##                                                       
##   Test statistic                                 0.000
##   Degrees of freedom                                 0
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Regressions:
##                    Estimate   Std.Err  z-value  P(&gt;|z|)
##   RT ~                                                 
##     HH               100.750   40.085    2.513    0.012
##     HF                63.800   40.085    1.592    0.111
## 
## Intercepts:
##                    Estimate   Std.Err  z-value  P(&gt;|z|)
##    .RT               553.750   28.344   19.537    0.000
## 
## Variances:
##                    Estimate   Std.Err  z-value  P(&gt;|z|)
##    .RT             16068.028 2933.607    5.477    0.000</code></pre>
<p>Alternatively, we can combine the data processing and model estimation into a single pipeline, as shown below.</p>
<ul>
<li>This type of combined approach might be preferable if we do not want to permanently add the dummy codes to the
<code>drivers</code> dataset.</li>
<li>The multi-step approach shown above would be better if we were going to reuse the dummy codes in subsequent analyses.</li>
</ul>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="in-class-exercises-1.html#cb60-1" tabindex="-1"></a>lavOut2 <span class="ot">&lt;-</span> drivers <span class="sc">|&gt;</span></span>
<span id="cb60-2"><a href="in-class-exercises-1.html#cb60-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">HH =</span> <span class="fu">ifelse</span>(condition <span class="sc">==</span> <span class="st">&quot;hand-held&quot;</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb60-3"><a href="in-class-exercises-1.html#cb60-3" tabindex="-1"></a>         <span class="at">HF =</span> <span class="fu">ifelse</span>(condition <span class="sc">==</span> <span class="st">&quot;hands-free&quot;</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb60-4"><a href="in-class-exercises-1.html#cb60-4" tabindex="-1"></a>         ) <span class="sc">|&gt;</span></span>
<span id="cb60-5"><a href="in-class-exercises-1.html#cb60-5" tabindex="-1"></a>  <span class="fu">sem</span>(mod, <span class="at">data =</span> _) <span class="co"># Estimate the model</span></span>
<span id="cb60-6"><a href="in-class-exercises-1.html#cb60-6" tabindex="-1"></a></span>
<span id="cb60-7"><a href="in-class-exercises-1.html#cb60-7" tabindex="-1"></a><span class="do">## Do the two approaches produce the same results?</span></span>
<span id="cb60-8"><a href="in-class-exercises-1.html#cb60-8" tabindex="-1"></a><span class="fu">all.equal</span>(</span>
<span id="cb60-9"><a href="in-class-exercises-1.html#cb60-9" tabindex="-1"></a>  <span class="fu">parameterEstimates</span>(lavOut), </span>
<span id="cb60-10"><a href="in-class-exercises-1.html#cb60-10" tabindex="-1"></a>  <span class="fu">parameterEstimates</span>(lavOut2)</span>
<span id="cb60-11"><a href="in-class-exercises-1.html#cb60-11" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="in-class-exercises-1.html#cb62-1" tabindex="-1"></a><span class="fu">all.equal</span>(</span>
<span id="cb62-2"><a href="in-class-exercises-1.html#cb62-2" tabindex="-1"></a>  <span class="fu">fitMeasures</span>(lavOut), </span>
<span id="cb62-3"><a href="in-class-exercises-1.html#cb62-3" tabindex="-1"></a>  <span class="fu">fitMeasures</span>(lavOut2)</span>
<span id="cb62-4"><a href="in-class-exercises-1.html#cb62-4" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>At this point, we haven’t covered the tools you need to conduct the ANOVA-style tests with path models. So, you can’t
yet answer the research question with the above model.</p>
<ul>
<li>When we discuss model comparisons, you’ll get the missing tools.</li>
</ul>
</details>
<hr />
<p>End of In-Class Exercises</p>
<hr />

</div>
</div>
</div>
<!-- </div> -->
            </section>

          </div>
        </div>
      </div>
<a href="at-home-exercises-1.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="mediation-moderation.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": false,
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section",
    "search": true
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
